'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { CommonModal } from '@/components/ui/common-modal';
import { fetchDecorationCategories, fetchDecorationItems, removeDecorationItemImage, saveDecorationCategory, saveDecorationItem, setDecorationCategoryActive, setDecorationItemActive, setDecorationItemCoverImage, uploadDecorationItemImage } from '@/lib/auth/api';
import { hasPermission, PERMISSIONS } from '@/lib/auth/permissions';
import type { DecorationCategory, DecorationItem } from '@/lib/auth/types';
import { buildDecorationItemPayload, type DecorationCategoryForm, type SimpleDecorationItemForm, validateDecorationCategoryForm, validateDecorationItemForm } from '@/lib/decoration/catalog-form';
import { getDecorationCoverImage, validateDecorationImageFile } from '@/lib/decoration/catalog-images';
import { createDecorationItemWithOptionalImage } from '@/lib/decoration/create-item-workflow';

const field = 'mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100';
const emptyItem = (categoryId = ''): SimpleDecorationItemForm => ({ categoryId, name: '', description: '', totalQuantity: '1' });

export function DecorationCatalogSection() {
  const { accessToken, user } = useAuth(); const manage = user?.role === 'company_admin' || hasPermission(user, PERMISSIONS.DECORATION_CATALOG_MANAGE);
  const [categories, setCategories] = useState<DecorationCategory[]>([]), [items, setItems] = useState<DecorationItem[]>([]), [selected, setSelected] = useState(''), [includeInactive, setIncludeInactive] = useState(false);
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [categoryModal, setCategoryModal] = useState<DecorationCategory | 'new' | null>(null), [itemModal, setItemModal] = useState<DecorationItem | 'new' | null>(null);
  const load = useCallback(async () => { if (!accessToken) return; setLoading(true); setError(''); try { const [nextCategories, nextItems] = await Promise.all([fetchDecorationCategories(accessToken, includeInactive), fetchDecorationItems(accessToken, selected, includeInactive)]); setCategories(nextCategories); setItems(nextItems); if (selected && !nextCategories.some((category) => category.id === selected)) setSelected(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load decoration catalog.'); } finally { setLoading(false); } }, [accessToken, includeInactive, selected]);
  useEffect(() => { void load(); }, [load]);
  async function change(action: () => Promise<unknown>) { setError(''); try { await action(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update decoration catalog.'); throw reason; } }
  const visibleItems = selected ? items.filter((item) => item.categoryId === selected) : items;
  return <section className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-bold text-slate-950">Decoration</h2><p className="text-sm text-slate-500">Create decoration types, then add reusable items with images and quantities.</p></div>{manage ? <div className="flex flex-wrap gap-2"><button type="button" onClick={() => setCategoryModal('new')} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-slate-800">Add type</button><button type="button" disabled={!selected} onClick={() => setItemModal('new')} className="rounded-xl bg-amber-500 px-4 py-3 text-sm font-bold text-slate-950 disabled:opacity-40">Add item</button></div> : null}</div>
    {error ? <div role="alert" className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span>{error}</span><button onClick={() => void load()} className="font-bold underline">Retry</button></div> : null}
    <div className="flex items-center justify-between gap-3"><div className="flex min-w-0 flex-1 gap-2 overflow-x-auto pb-1"><TypeChip active={!selected} onClick={() => setSelected('')}>All</TypeChip>{categories.map((category) => <TypeChip key={category.id} active={selected === category.id} muted={!category.isActive} onClick={() => setSelected(category.id)}>{category.name}</TypeChip>)}</div><label className="flex shrink-0 items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={includeInactive} onChange={(event) => setIncludeInactive(event.target.checked)} />Inactive</label></div>
    {loading && !items.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map((key) => <div key={key} className="h-52 animate-pulse rounded-2xl bg-slate-100" />)}</div> : visibleItems.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visibleItems.map((item) => <CatalogItemCard key={item.id} item={item} categoryName={categories.find((category) => category.id === item.categoryId)?.name ?? 'Decoration'} manage={manage} token={accessToken} onEdit={() => setItemModal(item)} onChanged={(updated) => setItems((current) => current.map((entry) => entry.id === updated.id ? updated : entry))} onError={setError} onToggle={() => accessToken && void change(() => setDecorationItemActive(accessToken, item.id, !item.isActive))} />)}</div> : <p className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">{selected ? 'No items in this decoration type yet.' : 'Select a decoration type or add your first type.'}</p>}
    {manage && categories.length ? <div className="grid gap-3 sm:grid-cols-2">{categories.map((category) => <div key={category.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-3"><div><b>{category.name}</b><p className="text-xs text-slate-500">{category.isActive ? 'Active' : 'Inactive'}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setCategoryModal(category)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-800">Edit</button><button onClick={() => accessToken && void change(() => setDecorationCategoryActive(accessToken, category.id, !category.isActive))} className="rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-800">{category.isActive ? 'Deactivate' : 'Activate'}</button></div></div>)}</div> : null}
    {categoryModal ? <CategoryModal value={categoryModal} onClose={() => setCategoryModal(null)} onSave={async (form) => { if (!accessToken) return; await change(() => saveDecorationCategory(accessToken, { name: form.name.trim(), ...(form.description.trim() ? { description: form.description.trim() } : {}) }, categoryModal === 'new' ? undefined : categoryModal.id)); setCategoryModal(null); }} /> : null}
    {itemModal ? <ItemModal value={itemModal} categoryId={selected} onClose={() => setItemModal(null)} onSave={async (form, image) => { if (!accessToken) return; if (itemModal === 'new') { const result = await createDecorationItemWithOptionalImage({ payload: buildDecorationItemPayload(form), image, createItem: (payload) => saveDecorationItem(accessToken, payload), uploadImage: (id, file) => uploadDecorationItemImage(accessToken, id, file) }); await load(); setItemModal(null); if (result.warning) setError(result.warning); return; } await saveDecorationItem(accessToken, buildDecorationItemPayload(form), itemModal.id); await load(); setItemModal(null); }} /> : null}
  </section>;
}

function TypeChip({ active, muted, onClick, children }: { active: boolean; muted?: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${active ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700'} ${muted ? 'opacity-50' : ''}`}>{children}</button>; }

function CatalogItemCard({ item, categoryName, manage, token, onEdit, onChanged, onError, onToggle }: { item: DecorationItem; categoryName: string; manage: boolean; token: string | null; onEdit: () => void; onChanged: (item: DecorationItem) => void; onError: (error: string) => void; onToggle: () => void }) {
  const [busy, setBusy] = useState(false), [broken, setBroken] = useState(false); const cover = getDecorationCoverImage(item.images);
  async function run(action: () => Promise<DecorationItem>) { if (busy) return; setBusy(true); onError(''); try { onChanged(await action()); setBroken(false); } catch (reason) { onError(reason instanceof Error ? reason.message : 'Unable to update item images.'); } finally { setBusy(false); } }
  async function upload(file: File) { const validation = validateDecorationImageFile(file, item.images.length); if (validation) { onError(validation); return; } if (token) await run(() => uploadDecorationItemImage(token, item.id, file)); }
  return <article className={`overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm ${item.isActive ? '' : 'opacity-60'}`}><div className="aspect-[16/10] bg-slate-100">{cover && !broken ? <img src={cover.url} alt={item.name} onError={() => setBroken(true)} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-sm text-slate-400">No image available</div>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-950">{item.name}</h3><p className="mt-1 text-xs text-slate-500">{categoryName}</p></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">{item.availableQuantity}/{item.totalQuantity}</span></div>{item.description ? <p className="mt-3 text-sm text-slate-600">{item.description}</p> : null}{item.images.length ? <div className="mt-3 flex gap-2 overflow-x-auto pb-1">{item.images.map((image) => <div key={image.id} className="relative shrink-0"><img src={image.url} alt="" className={`h-16 w-16 rounded-lg object-cover ${image.isCover ? 'ring-2 ring-amber-500' : ''}`} />{manage ? <div className="mt-1 flex gap-1">{!image.isCover ? <button disabled={busy} onClick={() => token && void run(() => setDecorationItemCoverImage(token, item.id, image.id))} className="text-[10px] font-semibold text-slate-600">Cover</button> : <span className="text-[10px] font-semibold text-amber-700">Cover</span>}<button disabled={busy} onClick={() => token && void run(() => removeDecorationItemImage(token, item.id, image.id))} className="text-[10px] font-semibold text-red-600">Remove</button></div> : null}</div>)}</div> : null}{manage ? <div className="mt-4 flex flex-wrap gap-2"><button onClick={onEdit} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-800">Edit</button><label className={`cursor-pointer rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-800 ${busy ? 'pointer-events-none opacity-50' : ''}`}>{busy ? 'Uploading…' : 'Camera / gallery'}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void upload(file); }} /></label><button onClick={onToggle} className="rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-800">{item.isActive ? 'Deactivate' : 'Activate'}</button></div> : null}</div></article>;
}

function CategoryModal({ value, onClose, onSave }: { value: DecorationCategory | 'new'; onClose: () => void; onSave: (form: DecorationCategoryForm) => Promise<void> }) {
  const [form, setForm] = useState<DecorationCategoryForm>({ name: value === 'new' ? '' : value.name, description: value === 'new' ? '' : value.description ?? '' }), [errors, setErrors] = useState<{ name?: string }>({}), [saving, setSaving] = useState(false), [requestError, setRequestError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); const next = validateDecorationCategoryForm(form); setErrors(next); if (Object.keys(next).length) return; setSaving(true); setRequestError(''); try { await onSave(form); } catch (reason) { setRequestError(reason instanceof Error ? reason.message : 'Unable to save decoration type.'); } finally { setSaving(false); } }
  return <CommonModal title={value === 'new' ? 'Add decoration type' : 'Edit decoration type'} onClose={onClose} widthClassName="max-w-lg"><form onSubmit={submit} className="space-y-4">{requestError ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{requestError}</p> : null}<Field label="Type name" error={errors.name}><input autoFocus maxLength={100} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className={field} /></Field><Field label="Description (optional)"><textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className={field} /></Field><button disabled={saving} className="w-full rounded-xl bg-amber-500 p-3 font-bold text-slate-950 disabled:opacity-50">{saving ? 'Saving…' : 'Save type'}</button></form></CommonModal>;
}

function ItemModal({ value, categoryId, onClose, onSave }: { value: DecorationItem | 'new'; categoryId: string; onClose: () => void; onSave: (form: SimpleDecorationItemForm, image: File | null) => Promise<void> }) {
  const initial = value === 'new' ? emptyItem(categoryId) : { categoryId: value.categoryId, name: value.name, description: value.description ?? '', totalQuantity: String(value.totalQuantity) };
  const [form, setForm] = useState<SimpleDecorationItemForm>(initial), [errors, setErrors] = useState<Partial<Record<keyof SimpleDecorationItemForm, string>>>({}), [image, setImage] = useState<File | null>(null), [imageError, setImageError] = useState(''), [preview, setPreview] = useState(''), [saving, setSaving] = useState(false), [requestError, setRequestError] = useState('');
  useEffect(() => { if (!image) { setPreview(''); return; } const url = URL.createObjectURL(image); setPreview(url); return () => URL.revokeObjectURL(url); }, [image]);
  function set(key: keyof SimpleDecorationItemForm, next: string) { setForm((current) => ({ ...current, [key]: next })); setErrors((current) => ({ ...current, [key]: undefined })); }
  function selectImage(file: File) { const validation = validateDecorationImageFile(file, 0); if (validation) { setImageError(validation); return; } setImageError(''); setImage(file); }
  async function submit(event: FormEvent) { event.preventDefault(); const next = validateDecorationItemForm(form); setErrors(next); if (Object.keys(next).length || imageError) return; setSaving(true); setRequestError(''); try { await onSave(form, image); } catch (reason) { setRequestError(reason instanceof Error ? reason.message : 'Unable to save decoration item.'); } finally { setSaving(false); } }
  return <CommonModal title={value === 'new' ? 'Add decoration item' : 'Edit decoration item'} onClose={() => { if (!saving) onClose(); }}><form onSubmit={submit} className="space-y-4">{requestError ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{requestError}</p> : null}<div className="grid gap-4 sm:grid-cols-2"><Field label="Item name" error={errors.name}><input autoFocus value={form.name} onChange={(event) => set('name', event.target.value)} className={field} /></Field><Field label="Total quantity" error={errors.totalQuantity}><input type="number" inputMode="numeric" min="1" value={form.totalQuantity} onChange={(event) => set('totalQuantity', event.target.value)} className={field} /></Field></div><Field label="Description (optional)"><textarea rows={3} value={form.description} onChange={(event) => set('description', event.target.value)} className={field} /></Field>{value === 'new' ? <div><p className="text-sm font-semibold text-slate-700">Item image (optional)</p>{preview ? <div className="mt-2 flex items-center gap-3 rounded-xl border p-3"><img src={preview} alt="Selected item preview" className="h-24 w-24 rounded-lg object-cover" /><div><p className="max-w-[220px] truncate text-sm font-semibold">{image?.name}</p><button type="button" disabled={saving} onClick={() => setImage(null)} className="mt-2 text-xs font-bold text-red-600">Remove image</button></div></div> : <label className="mt-2 flex min-h-28 cursor-pointer items-center justify-center rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 text-center text-sm font-bold text-slate-700">Camera / gallery<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ''; if (file) selectImage(file); }} /></label>}{imageError ? <p className="mt-1 text-xs text-red-600">{imageError}</p> : null}</div> : null}<button disabled={saving} className="w-full rounded-xl bg-amber-500 p-3 font-bold text-slate-950 disabled:opacity-50">{saving ? image ? 'Saving item and image…' : 'Saving item…' : 'Save item'}</button></form></CommonModal>;
}

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-700">{label}{children}{error ? <span className="mt-1 block text-xs font-normal text-red-600">{error}</span> : null}</label>; }
