'use client';

import { FormEvent, useCallback, useEffect, useRef, useState, type ComponentType, type RefObject } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { DecorationImageCropModal } from '@/components/decoration/decoration-image-crop-modal';
import { CommonModal } from '@/components/ui/common-modal';
import { fetchDecorationCategories, fetchDecorationItems, removeDecorationItemImage, saveDecorationCategory, saveDecorationItem, setDecorationCategoryActive, setDecorationItemActive, setDecorationItemCoverImage, uploadDecorationItemImage } from '@/lib/auth/api';
import { hasPermission, PERMISSIONS } from '@/lib/auth/permissions';
import type { DecorationCategory, DecorationImageDisplayMode, DecorationItem } from '@/lib/auth/types';
import { buildDecorationItemPayload, type DecorationCategoryForm, type SimpleDecorationItemForm, validateDecorationCategoryForm, validateDecorationItemForm } from '@/lib/decoration/catalog-form';
import { getDecorationCoverImage, materializeDecorationImageFile, validateDecorationImageFile } from '@/lib/decoration/catalog-images';
import { createDecorationItemWithOptionalImage } from '@/lib/decoration/create-item-workflow';
import { childrenForParent, decorationPreviewImages, reconcileSelectedParentId } from '@/lib/decoration/settings-view';
import { decorationImageFitClass } from '@/lib/decoration/image-display-mode';

const field = 'light-form-field mt-1 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100';
const emptyItem = (categoryId = ''): SimpleDecorationItemForm => ({ categoryId, name: '', description: '', totalQuantity: '1' });

export type CatalogCropModalProps = { file: File; busy?: boolean; returnFocusRef?: RefObject<HTMLElement | null>; onCancel: () => void; onConfirm: (file: File, displayMode: DecorationImageDisplayMode) => void | Promise<void> };

export function DecorationCatalogSection() {
  const { accessToken, user } = useAuth(); const manage = user?.role === 'company_admin' || hasPermission(user, PERMISSIONS.DECORATION_CATALOG_MANAGE);
  const [categories, setCategories] = useState<DecorationCategory[]>([]), [items, setItems] = useState<DecorationItem[]>([]), [selectedTypeId, setSelectedTypeId] = useState(''), [includeInactive, setIncludeInactive] = useState(false);
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [categoryModal, setCategoryModal] = useState<DecorationCategory | 'new' | null>(null), [itemModal, setItemModal] = useState<DecorationItem | 'new' | null>(null);
  const load = useCallback(async () => { if (!accessToken) return; setLoading(true); setError(''); try { const [nextCategories, nextItems] = await Promise.all([fetchDecorationCategories(accessToken, includeInactive), fetchDecorationItems(accessToken, '', includeInactive)]); setCategories(nextCategories); setItems(nextItems); setSelectedTypeId((current) => reconcileSelectedParentId(current, nextCategories)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load decoration catalog.'); } finally { setLoading(false); } }, [accessToken, includeInactive]);
  useEffect(() => { void load(); }, [load]);
  async function change(action: () => Promise<unknown>) { setError(''); try { await action(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update decoration catalog.'); throw reason; } }
  const selectedType = categories.find((category) => category.id === selectedTypeId);
  const selectedItems = selectedType ? childrenForParent(items, selectedType.id) : [];
  return <section className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div>{selectedType ? <button type="button" onClick={() => setSelectedTypeId('')} className="mb-2 inline-flex min-h-10 items-center rounded-lg border border-slate-300 bg-white px-3 text-sm font-bold text-slate-800">← Back to Decoration Types</button> : null}<h2 className="text-xl font-bold text-slate-950">{selectedType ? selectedType.name : 'Decoration Types'}</h2><p className="text-sm text-slate-600">{selectedType ? 'Manage the reusable items available within this decoration type.' : 'Open a decoration type to view and manage its items.'}</p></div>{selectedType ? manage ? <div className="flex flex-wrap gap-2"><button type="button" onClick={() => setCategoryModal(selectedType)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-4 text-sm font-bold text-slate-800">Edit type</button><button type="button" onClick={() => setItemModal('new')} className="min-h-11 rounded-xl bg-amber-500 px-4 text-sm font-bold text-slate-950">Add item</button></div> : null : manage ? <button type="button" onClick={() => setCategoryModal('new')} className="min-h-11 rounded-xl bg-amber-500 px-4 text-sm font-bold text-slate-950">Add type</button> : null}</div>
    {error ? <div role="alert" className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><span>{error}</span><button onClick={() => void load()} className="font-bold underline">Retry</button></div> : null}
    {!selectedType ? <label className="flex w-fit items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={includeInactive} onChange={(event) => setIncludeInactive(event.target.checked)} />Show inactive types</label> : null}
    {loading && !categories.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map((key) => <div key={key} className="h-64 animate-pulse rounded-2xl bg-slate-100" />)}</div> : selectedType ? selectedItems.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{selectedItems.map((item) => <CatalogItemCard key={item.id} item={item} categoryName={selectedType.name} manage={manage} token={accessToken} onEdit={() => setItemModal(item)} onChanged={(updated) => setItems((current) => current.map((entry) => entry.id === updated.id ? updated : entry))} onError={setError} onToggle={() => accessToken && void change(() => setDecorationItemActive(accessToken, item.id, !item.isActive))} />)}</div> : <p className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-600">No items in this decoration type yet.{manage ? ' Use Add item to create the first one.' : ''}</p> : categories.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((category) => <DecorationTypeCard key={category.id} category={category} items={childrenForParent(items, category.id)} manage={manage} onOpen={() => setSelectedTypeId(category.id)} onEdit={() => setCategoryModal(category)} onToggle={() => accessToken && void change(() => setDecorationCategoryActive(accessToken, category.id, !category.isActive))} />)}</div> : <p className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-600">No decoration types configured yet.</p>}
    {categoryModal ? <CategoryModal value={categoryModal} onClose={() => setCategoryModal(null)} onSave={async (form) => { if (!accessToken) return; await change(() => saveDecorationCategory(accessToken, { name: form.name.trim(), ...(form.description.trim() ? { description: form.description.trim() } : {}) }, categoryModal === 'new' ? undefined : categoryModal.id)); setCategoryModal(null); }} /> : null}
    {itemModal && selectedType ? <ItemModal value={itemModal} categoryId={selectedType.id} onClose={() => setItemModal(null)} onSave={async (form, image, displayMode) => { if (!accessToken) return; if (itemModal === 'new') { const result = await createDecorationItemWithOptionalImage({ payload: buildDecorationItemPayload({ ...form, categoryId: selectedType.id }), image, createItem: (payload) => saveDecorationItem(accessToken, payload), uploadImage: (id, file) => uploadDecorationItemImage(accessToken, id, file, displayMode) }); await load(); setItemModal(null); if (result.warning) setError(result.warning); return; } await saveDecorationItem(accessToken, buildDecorationItemPayload({ ...form, categoryId: selectedType.id }), itemModal.id); await load(); setItemModal(null); }} /> : null}
  </section>;
}

function DecorationTypeCard({ category, items, manage, onOpen, onEdit, onToggle }: { category: DecorationCategory; items: DecorationItem[]; manage: boolean; onOpen: () => void; onEdit: () => void; onToggle: () => void }) {
  const previews = decorationPreviewImages(items);
  const [imageIndex, setImageIndex] = useState(0);
  const activeIndex = previews.length ? Math.min(imageIndex, previews.length - 1) : 0;
  const activePreview = previews[activeIndex];
  const activePreviewMode = items
    .flatMap((item) => item.images)
    .find((image) => image.url === activePreview)?.displayMode;
  return <article className={`overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm ${category.isActive ? '' : 'opacity-70'}`}><div className="relative aspect-[16/9] bg-slate-100">{activePreview ? <img src={activePreview} alt={`${category.name} item preview`} className={`h-full w-full ${decorationImageFitClass(activePreviewMode)}`} /> : <div className="flex h-full items-center justify-center px-4 text-center text-sm font-medium text-slate-500">Add item images to preview this type</div>}{previews.length > 1 ? <><button type="button" aria-label="Previous item image" onClick={() => setImageIndex((current) => (current - 1 + previews.length) % previews.length)} className="absolute left-2 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-slate-950/80 text-xl font-bold text-white">‹</button><button type="button" aria-label="Next item image" onClick={() => setImageIndex((current) => (current + 1) % previews.length)} className="absolute right-2 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center rounded-full bg-slate-950/80 text-xl font-bold text-white">›</button></> : null}</div><div className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-950">{category.name}</h3><p className="text-sm text-slate-600">{items.length} {items.length === 1 ? 'item' : 'items'}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${category.isActive ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{category.isActive ? 'Active' : 'Inactive'}</span></div>{category.description ? <p className="line-clamp-2 text-sm text-slate-600">{category.description}</p> : null}<button type="button" onClick={onOpen} className="min-h-11 w-full rounded-xl bg-slate-950 px-4 text-sm font-bold text-white">Open Type</button>{manage ? <div className="grid grid-cols-2 gap-2"><button type="button" onClick={onEdit} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 text-xs font-bold text-slate-800">Edit</button><button type="button" onClick={onToggle} className="min-h-10 rounded-lg border border-slate-300 bg-slate-50 px-3 text-xs font-bold text-slate-800">{category.isActive ? 'Deactivate' : 'Activate'}</button></div> : null}</div></article>;
}

export function CatalogItemCard({ item, categoryName, manage, token, onEdit, onChanged, onError, onToggle, CropModal = DecorationImageCropModal, uploadImage = uploadDecorationItemImage, materializeImage = materializeDecorationImageFile }: { item: DecorationItem; categoryName: string; manage: boolean; token: string | null; onEdit: () => void; onChanged: (item: DecorationItem) => void; onError: (error: string) => void; onToggle: () => void; CropModal?: ComponentType<CatalogCropModalProps>; uploadImage?: typeof uploadDecorationItemImage; materializeImage?: typeof materializeDecorationImageFile }) {
  const [busy, setBusy] = useState(false), [broken, setBroken] = useState(false), [pendingSource, setPendingSource] = useState<File | null>(null), [confirmedCrop, setConfirmedCrop] = useState<{ file: File; displayMode: DecorationImageDisplayMode } | null>(null); const cover = getDecorationCoverImage(item.images);
  const mountedRef = useRef(true), itemRef = useRef(item), itemIdRef = useRef(item.id), generationRef = useRef(0), uploadLockRef = useRef(false), selectionRef = useRef(0), triggerRef = useRef<HTMLButtonElement | null>(null), fileInputRef = useRef<HTMLInputElement | null>(null), focusRestoreRef = useRef<{ generation: number; itemId: string } | null>(null);
  useEffect(() => {
    itemRef.current = item;
    if (itemIdRef.current === item.id) return;
    itemIdRef.current = item.id;
    generationRef.current += 1;
    selectionRef.current += 1;
    uploadLockRef.current = false;
    focusRestoreRef.current = null;
    setPendingSource(null);
    setConfirmedCrop(null);
    setBusy(false);
  }, [item]);
  useEffect(() => { mountedRef.current = true; return () => { mountedRef.current = false; generationRef.current += 1; selectionRef.current += 1; uploadLockRef.current = false; focusRestoreRef.current = null; }; }, []);
  useEffect(() => {
    const request = focusRestoreRef.current;
    if (busy || !request) return;
    focusRestoreRef.current = null;
    queueMicrotask(() => {
      if (!mountedRef.current || request.generation !== generationRef.current || request.itemId !== itemIdRef.current) return;
      const active = document.activeElement;
      if (active && active !== document.body && active.isConnected) return;
      const trigger = triggerRef.current;
      if (trigger && !trigger.disabled) trigger.focus();
    });
  }, [busy, confirmedCrop]);
  async function run(action: () => Promise<DecorationItem>) { if (busy) return; setBusy(true); onError(''); try { onChanged(await action()); setBroken(false); } catch (reason) { onError(reason instanceof Error ? reason.message : 'Unable to update item images.'); } finally { setBusy(false); } }
  async function selectSource(file: File) { const selection = ++selectionRef.current; const validation = validateDecorationImageFile(file, itemRef.current.images.length); if (validation) { onError(validation); return; } try { const stableFile = await materializeImage(file); if (!mountedRef.current || selection !== selectionRef.current) return; setPendingSource(stableFile); onError(''); } catch (error) { if (mountedRef.current && selection === selectionRef.current) onError(error instanceof Error ? error.message : 'The selected image could not be read.'); } }
  async function uploadConfirmed(file: File, displayMode: DecorationImageDisplayMode, revalidate = true) { if (!token || uploadLockRef.current) return; uploadLockRef.current = true; const generation = generationRef.current; const id = itemIdRef.current; const fileValidation = validateDecorationImageFile(file, revalidate ? 0 : itemRef.current.images.length); if (fileValidation) { onError(fileValidation); uploadLockRef.current = false; return; } focusRestoreRef.current = { generation, itemId: id }; setBusy(true); onError(''); try { const stableFile = revalidate ? await materializeImage(file) : file; if (!mountedRef.current || generation !== generationRef.current || id !== itemIdRef.current) return; if (revalidate) { setConfirmedCrop({ file: stableFile, displayMode }); setPendingSource(null); } const latestValidation = validateDecorationImageFile(stableFile, itemRef.current.images.length); if (latestValidation) { onError(latestValidation); return; } const updated = await uploadImage(token, id, stableFile, displayMode); if (!mountedRef.current || generation !== generationRef.current || id !== itemIdRef.current) return; onChanged(updated); setBroken(false); setConfirmedCrop(null); } catch (reason) { if (mountedRef.current && generation === generationRef.current && id === itemIdRef.current) onError(reason instanceof Error ? reason.message : 'Unable to upload item image.'); } finally { if (mountedRef.current && generation === generationRef.current) setBusy(false); uploadLockRef.current = false; } }
  return <>
    <article className={`overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm ${item.isActive ? '' : 'opacity-60'}`}>
      <div className="aspect-[16/10] bg-slate-100">{cover && !broken ? <img src={cover.url} alt={item.name} onError={() => setBroken(true)} className={`h-full w-full ${decorationImageFitClass(cover.displayMode)}`} /> : <div className="flex h-full items-center justify-center text-sm text-slate-400">No image available</div>}</div>
      <div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-950">{item.name}</h3><p className="mt-1 text-xs text-slate-500">{categoryName}</p></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">{item.availableQuantity}/{item.totalQuantity}</span></div>
        {item.description ? <p className="mt-3 text-sm text-slate-600">{item.description}</p> : null}
        {item.images.length ? <div className="mt-3 flex gap-2 overflow-x-auto pb-1">{item.images.map((image) => <div key={image.id} className="relative shrink-0"><img src={image.url} alt="" className={`h-16 w-16 rounded-lg bg-slate-100 ${decorationImageFitClass(image.displayMode)} ${image.isCover ? 'ring-2 ring-amber-500' : ''}`} />{manage ? <div className="mt-1 flex gap-1">{!image.isCover ? <button disabled={busy} onClick={() => token && void run(() => setDecorationItemCoverImage(token, item.id, image.id))} className="text-[10px] font-semibold text-slate-600">Cover</button> : <span className="text-[10px] font-semibold text-amber-700">Cover</span>}<button disabled={busy} onClick={() => token && void run(() => removeDecorationItemImage(token, item.id, image.id))} className="text-[10px] font-semibold text-red-600">Remove</button></div> : null}</div>)}</div> : null}
        {manage ? <div className="mt-4 flex flex-wrap gap-2"><button onClick={onEdit} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-800">Edit</button><button ref={triggerRef} type="button" disabled={busy} onClick={() => fileInputRef.current?.click()} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-800 disabled:opacity-50">{busy ? 'Uploading…' : 'Camera / gallery'}</button><input ref={fileInputRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void selectSource(file); }} />{confirmedCrop ? <button type="button" disabled={busy} onClick={() => void uploadConfirmed(confirmedCrop.file, confirmedCrop.displayMode, false)} aria-label="Retry image upload" className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">Retry upload</button> : null}<button onClick={onToggle} className="rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-xs font-bold text-slate-800">{item.isActive ? 'Deactivate' : 'Activate'}</button></div> : null}
      </div>
    </article>
    {pendingSource ? <CropModal file={pendingSource} busy={busy} returnFocusRef={triggerRef} onCancel={() => setPendingSource(null)} onConfirm={(file, displayMode) => uploadConfirmed(file, displayMode)} /> : null}
  </>;
}

function CategoryModal({ value, onClose, onSave }: { value: DecorationCategory | 'new'; onClose: () => void; onSave: (form: DecorationCategoryForm) => Promise<void> }) {
  const [form, setForm] = useState<DecorationCategoryForm>({ name: value === 'new' ? '' : value.name, description: value === 'new' ? '' : value.description ?? '' }), [errors, setErrors] = useState<{ name?: string }>({}), [saving, setSaving] = useState(false), [requestError, setRequestError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); const next = validateDecorationCategoryForm(form); setErrors(next); if (Object.keys(next).length) return; setSaving(true); setRequestError(''); try { await onSave(form); } catch (reason) { setRequestError(reason instanceof Error ? reason.message : 'Unable to save decoration type.'); } finally { setSaving(false); } }
  return <CommonModal title={value === 'new' ? 'Add decoration type' : 'Edit decoration type'} onClose={onClose} widthClassName="max-w-lg"><form onSubmit={submit} className="space-y-4">{requestError ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{requestError}</p> : null}<Field label="Type name" error={errors.name}><input autoFocus maxLength={100} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className={field} /></Field><Field label="Description (optional)"><textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className={field} /></Field><button disabled={saving} className="w-full rounded-xl bg-amber-500 p-3 font-bold text-slate-950 disabled:opacity-50">{saving ? 'Saving…' : 'Save type'}</button></form></CommonModal>;
}

export function ItemModal({ value, categoryId, onClose, onSave, CropModal = DecorationImageCropModal, materializeImage = materializeDecorationImageFile }: { value: DecorationItem | 'new'; categoryId: string; onClose: () => void; onSave: (form: SimpleDecorationItemForm, image: File | null, displayMode: DecorationImageDisplayMode) => Promise<void>; CropModal?: ComponentType<CatalogCropModalProps>; materializeImage?: typeof materializeDecorationImageFile }) {
  const initial = value === 'new' ? emptyItem(categoryId) : { categoryId: value.categoryId, name: value.name, description: value.description ?? '', totalQuantity: String(value.totalQuantity) };
  const [form, setForm] = useState<SimpleDecorationItemForm>(initial), [errors, setErrors] = useState<Partial<Record<keyof SimpleDecorationItemForm, string>>>({}), [image, setImage] = useState<File | null>(null), [imageDisplayMode, setImageDisplayMode] = useState<DecorationImageDisplayMode>('COVER'), [pendingSource, setPendingSource] = useState<File | null>(null), [imageError, setImageError] = useState(''), [preview, setPreview] = useState(''), [saving, setSaving] = useState(false), [requestError, setRequestError] = useState('');
  const mountedRef = useRef(true), selectionRef = useRef(0), confirmLockRef = useRef(false), triggerRef = useRef<HTMLButtonElement | null>(null), fileInputRef = useRef<HTMLInputElement | null>(null);
  useEffect(() => { mountedRef.current = true; return () => { mountedRef.current = false; selectionRef.current += 1; confirmLockRef.current = false; }; }, []);
  useEffect(() => { if (!image) { setPreview(''); return; } const url = URL.createObjectURL(image); setPreview(url); return () => URL.revokeObjectURL(url); }, [image]);
  function set(key: keyof SimpleDecorationItemForm, next: string) { setForm((current) => ({ ...current, [key]: next })); setErrors((current) => ({ ...current, [key]: undefined })); }
  async function selectImage(file: File) { const selection = ++selectionRef.current; const validation = validateDecorationImageFile(file, 0); if (validation) { setImageError(validation); return; } try { const stableFile = await materializeImage(file); if (!mountedRef.current || selection !== selectionRef.current) return; setImageError(''); setPendingSource(stableFile); } catch (error) { if (mountedRef.current && selection === selectionRef.current) setImageError(error instanceof Error ? error.message : 'The selected image could not be read.'); } }
  async function confirmImage(selectedImage: File, displayMode: DecorationImageDisplayMode) { if (confirmLockRef.current) return; confirmLockRef.current = true; const selection = selectionRef.current; try { const stableFile = await materializeImage(selectedImage); if (!mountedRef.current || selection !== selectionRef.current) return; setImageError(''); setImage(stableFile); setImageDisplayMode(displayMode); setPendingSource(null); } catch (error) { if (mountedRef.current && selection === selectionRef.current) setImageError(error instanceof Error ? error.message : 'The selected image could not be read.'); } finally { confirmLockRef.current = false; } }
  async function submit(event: FormEvent) { event.preventDefault(); const next = validateDecorationItemForm(form); setErrors(next); if (Object.keys(next).length || imageError) return; setSaving(true); setRequestError(''); try { await onSave(form, image, imageDisplayMode); } catch (reason) { setRequestError(reason instanceof Error ? reason.message : 'Unable to save decoration item.'); } finally { setSaving(false); } }
  return <><CommonModal title={value === 'new' ? 'Add decoration item' : 'Edit decoration item'} onClose={() => { if (!saving) onClose(); }}><form onSubmit={submit} className="space-y-4">{requestError ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{requestError}</p> : null}<div className="grid gap-4 sm:grid-cols-2"><Field label="Item name" error={errors.name}><input autoFocus value={form.name} onChange={(event) => set('name', event.target.value)} className={field} /></Field><Field label="Total quantity" error={errors.totalQuantity}><input type="number" inputMode="numeric" min="1" value={form.totalQuantity} onChange={(event) => set('totalQuantity', event.target.value)} className={field} /></Field></div><Field label="Description (optional)"><textarea rows={3} value={form.description} onChange={(event) => set('description', event.target.value)} className={field} /></Field>{value === 'new' ? <div><p className="text-sm font-semibold text-slate-700">Item image (optional)</p><input ref={fileInputRef} aria-label="Item image file" type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void selectImage(file); }} />{preview ? <div className="mt-2 flex items-center gap-3 rounded-xl border p-3"><img src={preview} alt="Selected item preview" className={`h-24 w-24 rounded-lg bg-slate-100 ${decorationImageFitClass(imageDisplayMode)}`} /><div><p className="max-w-[220px] truncate text-sm font-semibold">{image?.name}</p><div className="mt-2 flex gap-3"><button ref={triggerRef} type="button" disabled={saving} onClick={() => fileInputRef.current?.click()} className="text-xs font-bold text-slate-700">Replace image</button><button type="button" disabled={saving} onClick={() => { selectionRef.current += 1; setPendingSource(null); setImage(null); setImageDisplayMode('COVER'); }} className="text-xs font-bold text-red-600">Remove image</button></div></div></div> : <button ref={triggerRef} type="button" disabled={saving} onClick={() => fileInputRef.current?.click()} className="mt-2 flex min-h-28 w-full items-center justify-center rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 text-center text-sm font-bold text-slate-700">Camera / gallery</button>}{imageError ? <p className="mt-1 text-xs text-red-600">{imageError}</p> : null}</div> : null}<button disabled={saving} className="w-full rounded-xl bg-amber-500 p-3 font-bold text-slate-950 disabled:opacity-50">{saving ? image ? 'Saving item and image…' : 'Saving item…' : 'Save item'}</button></form></CommonModal>{pendingSource ? <CropModal file={pendingSource} busy={saving} returnFocusRef={triggerRef} onCancel={() => setPendingSource(null)} onConfirm={confirmImage} /> : null}</>;
}

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-700">{label}{children}{error ? <span className="mt-1 block text-xs font-normal text-red-600">{error}</span> : null}</label>; }
