'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { BodyPortal } from '@/components/ui/body-portal';
import { DecorationCustomItemEditor } from './decoration-custom-item-editor';
import { DecorationSelectionItemCard } from './decoration-selection-item-card';
import { fetchDecorationCategories, fetchDecorationItems, saveDecorationSelection, uploadCustomDecorationImage } from '@/lib/auth/api';
import type { DecorationBooking, DecorationCategory, DecorationItem } from '@/lib/auth/types';
import { buildDecorationSelectionPayload, hydrateDecorationSelection, selectionSummary, toggleDecorationChoice, updateDecorationChoice, validateDecorationSelection, type DecorationSelectionState } from '@/lib/decoration/selection-state';

export function DecorationSelectionModal({ booking, onClose, onSaved }: { booking: DecorationBooking; onClose: () => void; onSaved: (booking: DecorationBooking) => void }) {
  const { accessToken } = useAuth(); const triggerRef = useRef<HTMLInputElement>(null);
  const [categories, setCategories] = useState<DecorationCategory[]>([]), [items, setItems] = useState<DecorationItem[]>([]), [categoryId, setCategoryId] = useState(''), [state, setState] = useState<DecorationSelectionState>({ choices: {}, customItems: [] });
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [uploading, setUploading] = useState(false), [error, setError] = useState(''), [errors, setErrors] = useState<ReturnType<typeof validateDecorationSelection>>({ choices: {}, custom: {} });
  useEffect(() => {
    const previous = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !saving && !uploading) onClose();
    };
    window.addEventListener('keydown', closeOnEscape);
    return () => {
      window.removeEventListener('keydown', closeOnEscape);
      document.body.style.overflow = previous;
    };
  }, [onClose, saving, uploading]);
  useEffect(() => { if (!accessToken) return; let active = true; setLoading(true); Promise.all([fetchDecorationCategories(accessToken), fetchDecorationItems(accessToken)]).then(([nextCategories, nextItems]) => { if (!active) return; setCategories(nextCategories); setItems(nextItems); setCategoryId(nextCategories[0]?.id ?? ''); setState(hydrateDecorationSelection(booking.decorationSnapshot ?? [], nextItems)); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : 'Unable to load decorations.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [accessToken, booking.id]);
  const shown = useMemo(() => items.filter((item) => item.categoryId === categoryId && item.isActive), [items, categoryId]), summary = selectionSummary(state);
  async function addCustom(file: File) { if (!accessToken || uploading) return; setUploading(true); setError(''); try { const image = await uploadCustomDecorationImage(accessToken, booking.id, file); setState((current) => ({ ...current, customItems: [...current.customItems, { clientId: crypto.randomUUID(), name: '', quantity: 1, description: '', imageKey: image.key, imageUrl: image.url }] })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to upload custom image.'); } finally { setUploading(false); } }
  async function save() { if (!accessToken || saving) return; const nextErrors = validateDecorationSelection(state, items); setErrors(nextErrors); if (Object.keys(nextErrors.choices).length || Object.keys(nextErrors.custom).length) { setError('Correct the highlighted selection details.'); return; } if (!summary.lineCount) { setError('Select at least one decoration.'); return; } setSaving(true); setError(''); const payload = buildDecorationSelectionPayload(state); try { const result = await saveDecorationSelection(accessToken, booking.id, payload.items, payload.customItems); onSaved(result.booking); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save decoration selection. Your choices are retained.'); } finally { setSaving(false); } }
  return <BodyPortal><div className="fixed inset-0 z-[75] flex items-end justify-center bg-slate-950/55 p-0 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="decoration-selection-title" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving && !uploading) onClose(); }}><div className="relative flex h-[100dvh] max-h-[100dvh] w-full max-w-6xl flex-col overflow-hidden rounded-t-3xl bg-slate-50 shadow-2xl sm:h-[calc(100dvh-2.5rem)] sm:max-h-[calc(100dvh-2.5rem)] sm:rounded-3xl"><header className="flex shrink-0 items-start justify-between gap-4 border-b bg-white p-4 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Decoration Selection</p><h2 id="decoration-selection-title" className="text-xl font-bold text-slate-950 sm:text-2xl">{booking.customer.name}</h2><p className="text-sm text-slate-500">{summary.lineCount} items · {summary.totalQuantity} total quantity</p></div><button onClick={onClose} disabled={saving || uploading} aria-label="Close Decoration Selection" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border bg-white text-2xl text-slate-500">×</button></header>
    <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-4 sm:p-6">{error ? <div role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div> : null}{loading ? <p className="py-16 text-center text-slate-500">Loading decoration types and availability…</p> : <><div className="flex gap-2 overflow-x-auto pb-3">{categories.map((category) => <button key={category.id} onClick={() => setCategoryId(category.id)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold ${categoryId === category.id ? 'bg-slate-900 text-white' : 'bg-white text-slate-700'}`}>{category.name}<span className="ml-2 rounded-full bg-black/10 px-2 py-0.5">{items.filter((item) => item.categoryId === category.id).length}</span></button>)}</div>{shown.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{shown.map((item) => <DecorationSelectionItemCard key={item.id} item={item} choice={state.choices[item.id]} error={errors.choices[item.id]} disabled={saving} onToggle={() => setState((current) => toggleDecorationChoice(current, item))} onChange={(patch) => setState((current) => updateDecorationChoice(current, item.id, patch))} />)}</div> : <p className="rounded-2xl border border-dashed p-8 text-center text-sm text-slate-500">No active items in this decoration type.</p>}<section className="mt-6 rounded-2xl border bg-white p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-slate-950">Custom Decoration</h3><p className="text-xs text-slate-500">For an event-specific item not present in the catalog.</p></div><label className={`cursor-pointer rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white ${uploading ? 'pointer-events-none opacity-60' : ''}`}>{uploading ? 'Uploading…' : 'Camera / gallery'}<input ref={triggerRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void addCustom(file); }} /></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{state.customItems.map((custom) => <DecorationCustomItemEditor key={custom.clientId} item={custom} errors={errors.custom[custom.clientId]} disabled={saving} onChange={(patch) => setState((current) => ({ ...current, customItems: current.customItems.map((entry) => entry.clientId === custom.clientId ? { ...entry, ...patch } : entry) }))} onRemove={() => setState((current) => ({ ...current, customItems: current.customItems.filter((entry) => entry.clientId !== custom.clientId) }))} />)}</div></section></>}</div>
    <footer className="safe-pad-bottom shrink-0 border-t bg-white/95 p-3 backdrop-blur sm:p-4"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><p className="hidden text-sm text-slate-500 sm:block">Availability is checked again when you save.</p><button disabled={loading || saving || uploading || !summary.lineCount} onClick={() => void save()} className="w-full rounded-xl bg-amber-500 px-6 py-3.5 font-bold text-slate-950 disabled:opacity-50 sm:w-auto">{saving ? 'Saving selection…' : `Save ${summary.lineCount} selections`}</button></div></footer></div></div></BodyPortal>;
}
