'use client';

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { DecorationConfirmationModal } from '@/components/decoration/decoration-confirmation-modal';
import { DecorationMoneyInput } from '@/components/decoration/decoration-money-input';
import { DecorationTimePicker } from '@/components/decoration/decoration-time-picker';
import { BodyPortal } from '@/components/ui/body-portal';
import { useModalViewport } from '@/components/ui/use-modal-viewport';
import { addDecorationHall, createConfirmedDecorationBooking, createDecorationEventType, createDecorationVenue, fetchDecorationEventTypes, fetchDecorationVenues, saveDecorationBooking } from '@/lib/auth/api';
import type { DecorationBooking, DecorationEventType, DecorationVenue } from '@/lib/auth/types';
import { activeHalls, decorationLocationTypeLabel, normalizeConfigurationName } from '@/lib/decoration/settings-view';
import { buildDecorationBookingPatch, changeInquiryLocation, createDecorationInquiryValues, OTHER_DECORATION_OPTION, validateDecorationInquiry, type DecorationInquiryValues } from '@/lib/decoration/inquiry-form';
import { decorationBusinessDate } from '@/lib/decoration/booking-date-policy';
import { cancelDecorationConfirmationDraft, createDecorationConfirmationDraft, submitDecorationConfirmationDraft, type DecorationConfirmationDraft } from '@/lib/decoration/create-confirmed-workflow';

const input='light-form-field min-h-12 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-amber-400 focus:ring-2 focus:ring-amber-100 disabled:bg-slate-50 disabled:text-slate-500';
function Field({label,error,children,required}:{label:string;error?:string;children:React.ReactNode;required?:boolean}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}{required?<span className="text-red-500"> *</span>:null}</span>{children}{error?<span className="mt-1 block text-xs font-semibold text-red-600">{error}</span>:null}</label>}

function bookingValues(booking:DecorationBooking):DecorationInquiryValues{return {...createDecorationInquiryValues(),customerName:booking.customer.name,mobile:booking.customer.mobile,alternativeMobile:booking.customer.alternativeMobile??'',eventTypeId:booking.eventType.id,venueId:booking.venue.id,hallId:booking.hall?.id??'',address:booking.address??'',timeSlot:booking.timeSlot,startTime:booking.startTime,endTime:booking.endTime,startDate:booking.startDate.slice(0,10),packageRate:booking.isPackagePriceFinalized?String(booking.packageRate):'',notes:booking.notes??''}}

export function DecorationInquiryForm({date,booking,onClose,onSaved}:{date?:string;booking?:DecorationBooking;onClose:()=>void;onSaved:(booking:DecorationBooking)=>void}){
 const{accessToken}=useAuth();const todayKey=decorationBusinessDate();const[initialValues]=useState<DecorationInquiryValues>(()=>booking?bookingValues(booking):createDecorationInquiryValues(date));const[values,setValues]=useState(initialValues),[types,setTypes]=useState<DecorationEventType[]>([]),[venues,setVenues]=useState<DecorationVenue[]>([]),[errors,setErrors]=useState<Partial<Record<keyof DecorationInquiryValues,string>>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[optionsLoading,setOptionsLoading]=useState(true),[pendingConfirmation,setPendingConfirmation]=useState<DecorationConfirmationDraft|null>(null);const submittingRef=useRef(false);
 useEffect(()=>{if(!accessToken)return;let active=true;setOptionsLoading(true);Promise.all([fetchDecorationEventTypes(accessToken),fetchDecorationVenues(accessToken)]).then(([eventTypes,locations])=>{if(active){setTypes(eventTypes);setVenues(locations)}}).catch(requestError=>{if(active)setError(requestError instanceof Error?requestError.message:'Unable to load form options')}).finally(()=>{if(active)setOptionsLoading(false)});return()=>{active=false}},[accessToken]);
 const venue=venues.find(item=>item.id===values.venueId);const halls=useMemo(()=>activeHalls(venues,values.venueId),[venues,values.venueId]);const set=<K extends keyof DecorationInquiryValues>(key:K,value:DecorationInquiryValues[K])=>{setValues(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:undefined}))};
 function requestClose(){const dirty=JSON.stringify(values)!==JSON.stringify(initialValues);if(!dirty||window.confirm('Discard the unsaved inquiry changes?'))onClose()}
 useModalViewport(()=>{if(!pendingConfirmation)requestClose()},busy||Boolean(pendingConfirmation));
 async function resolveConfiguration(){if(!accessToken)throw new Error('Session is unavailable');let resolved={...values};if(resolved.eventTypeId===OTHER_DECORATION_OPTION){const created=await createDecorationEventType(accessToken,{name:resolved.customEventTypeName},'INQUIRY_FORM');setTypes(current=>current.some(item=>item.id===created.id)?current:[...current,created]);resolved={...resolved,eventTypeId:created.id};setValues(resolved)}if(resolved.venueId===OTHER_DECORATION_OPTION){const created=await createDecorationVenue(accessToken,{name:resolved.customVenueName,type:resolved.customVenueType,address:resolved.customVenueAddress||undefined,halls:resolved.customHallName?[{name:resolved.customHallName}]:[]},'INQUIRY_FORM');setVenues(current=>current.some(item=>item.id===created.id)?current:[...current,created]);const createdHall=resolved.customHallName?created.halls.find(hall=>normalizeConfigurationName(hall.name)===normalizeConfigurationName(resolved.customHallName)):undefined;resolved={...resolved,venueId:created.id,hallId:createdHall?.id??'',address:resolved.address||resolved.customVenueAddress};setValues(resolved)}else if(resolved.hallId===OTHER_DECORATION_OPTION){const updated=await addDecorationHall(accessToken,resolved.venueId,resolved.customHallName,'INQUIRY_FORM');setVenues(current=>current.map(item=>item.id===updated.id?updated:item));const createdHall=updated.halls.find(hall=>normalizeConfigurationName(hall.name)===normalizeConfigurationName(resolved.customHallName));if(!createdHall)throw new Error('Created hall could not be resolved');resolved={...resolved,hallId:createdHall.id};setValues(resolved)}return resolved}
 async function submitIntent(intent:'INQUIRY'|'CONFIRMED'){if(submittingRef.current||!accessToken)return;const nextErrors=validateDecorationInquiry(values,{mode:booking?'edit':'create',todayKey});if(values.venueId!==OTHER_DECORATION_OPTION&&halls.length&&!values.hallId)nextErrors.hallId='Select a hall';setErrors(nextErrors);if(Object.keys(nextErrors).length)return;submittingRef.current=true;setBusy(true);setError('');try{const resolved=await resolveConfiguration();const payload=buildDecorationBookingPatch(booking?initialValues:null,resolved);if(intent==='CONFIRMED'&&!booking){setPendingConfirmation(createDecorationConfirmationDraft(payload,()=>crypto.randomUUID()));return}const saved=await saveDecorationBooking(accessToken,payload,booking?.id);onSaved(saved)}catch(requestError){setError(requestError instanceof Error?requestError.message:'Unable to save inquiry')}finally{submittingRef.current=false;setBusy(false)}}
 function submit(event:FormEvent){event.preventDefault();void submitIntent('INQUIRY')}
 return <BodyPortal><div className="modal-viewport-pad fixed inset-0 z-[70] flex items-center justify-center bg-slate-900/50 px-3 backdrop-blur-sm sm:px-4 sm:py-6" role="dialog" aria-modal="true" aria-label={booking?'Edit decoration inquiry':'Create decoration inquiry'}><div className="modal-panel-height safe-pad-bottom app-scrollbar relative w-full max-w-5xl overflow-y-auto rounded-2xl border border-slate-200 bg-white p-4 shadow-2xl sm:p-6"><button type="button" onClick={requestClose} aria-label="Close" className="absolute right-4 top-4 flex h-9 w-9 items-center justify-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-100 sm:right-6 sm:top-6">×</button><div className="pr-12"><p className="text-[10px] font-semibold uppercase tracking-widest text-amber-600">Inquiry Form</p><h2 className="mt-2 text-xl font-bold text-slate-900 sm:text-2xl">{booking?'Edit inquiry':'Create inquiry'}</h2></div>{error?<p role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>:null}
 <form onSubmit={submit} className="mt-6 space-y-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Customer Name" required error={errors.customerName}><input autoFocus disabled={busy} className={input} value={values.customerName} onChange={e=>set('customerName',e.target.value)}/></Field><Field label="Mobile Number" required error={errors.mobile}><input disabled={busy} inputMode="numeric" maxLength={10} className={input} value={values.mobile} onChange={e=>set('mobile',e.target.value.replace(/\D/g,''))}/></Field><Field label="Alternative Mobile Number (optional)" error={errors.alternativeMobile}><input disabled={busy} inputMode="numeric" maxLength={10} className={input} value={values.alternativeMobile} onChange={e=>set('alternativeMobile',e.target.value.replace(/\D/g,''))}/></Field>
 <Field label="Event Type" required error={errors.eventTypeId}><select disabled={busy||optionsLoading} className={input} value={values.eventTypeId} onChange={e=>set('eventTypeId',e.target.value)}><option value="">{optionsLoading?'Loading event types…':'Select event type'}</option>{types.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}<option value={OTHER_DECORATION_OPTION}>Other</option></select></Field>{values.eventTypeId===OTHER_DECORATION_OPTION?<Field label="Custom Event Type" required error={errors.customEventTypeName}><input disabled={busy} className={input} value={values.customEventTypeName} onChange={e=>set('customEventTypeName',e.target.value)}/></Field>:null}
 <Field label="Banquet / Outdoor Venue" required error={errors.venueId}><select disabled={busy||optionsLoading} className={input} value={values.venueId} onChange={e=>setValues(current=>changeInquiryLocation(current,e.target.value))}><option value="">{optionsLoading?'Loading locations…':'Select banquet / outdoor venue'}</option>{venues.map(item=><option key={item.id} value={item.id}>{item.name} ({decorationLocationTypeLabel(item.type)})</option>)}<option value={OTHER_DECORATION_OPTION}>Other</option></select></Field>
 {values.venueId===OTHER_DECORATION_OPTION?<><Field label="Location Type" required><select disabled={busy} className={input} value={values.customVenueType} onChange={e=>set('customVenueType',e.target.value as 'HOTEL'|'VENUE')}><option value="HOTEL">Banquet</option><option value="VENUE">Outdoor Venue</option></select></Field><Field label="Custom Banquet / Outdoor Venue Name" required error={errors.customVenueName}><input disabled={busy} className={input} value={values.customVenueName} onChange={e=>set('customVenueName',e.target.value)}/></Field><Field label="Location Address (optional)"><input disabled={busy} className={input} value={values.customVenueAddress} onChange={e=>set('customVenueAddress',e.target.value)}/></Field><Field label="Hall Name / Number (optional)"><input disabled={busy} className={input} value={values.customHallName} onChange={e=>set('customHallName',e.target.value)}/></Field></>:null}
 {venue&&(halls.length||values.hallId===OTHER_DECORATION_OPTION)?<Field label="Hall Name / Number" required={halls.length>0} error={errors.hallId}><select disabled={busy} className={input} value={values.hallId} onChange={e=>set('hallId',e.target.value)}><option value="">Select hall</option>{halls.map(hall=><option key={hall.id} value={hall.id}>{hall.name}</option>)}<option value={OTHER_DECORATION_OPTION}>Other</option></select></Field>:venue?<div className="flex items-end"><button type="button" disabled={busy} onClick={()=>set('hallId',OTHER_DECORATION_OPTION)} className="min-h-12 rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-700">Add hall (optional)</button></div>:null}
 {values.hallId===OTHER_DECORATION_OPTION&&values.venueId!==OTHER_DECORATION_OPTION?<Field label="Custom Hall Name / Number" required error={errors.customHallName}><input disabled={busy} className={input} value={values.customHallName} onChange={e=>set('customHallName',e.target.value)}/></Field>:null}
 <Field label="Time Slot" required><select disabled={busy} className={input} value={values.timeSlot} onChange={e=>set('timeSlot',e.target.value as DecorationInquiryValues['timeSlot'])}><option value="MORNING">Morning</option><option value="AFTERNOON">Afternoon</option><option value="EVENING">Evening</option></select></Field>
 <Field label="Event Date" required error={errors.startDate}><input disabled={busy} type="date" min={!booking?todayKey:undefined} className={input} value={values.startDate} onChange={e=>set('startDate',e.target.value)}/></Field>
 <Field label="Start Time" required error={errors.startTime}><DecorationTimePicker value={values.startTime} disabled={busy} onChange={value=>set('startTime',value)}/></Field>
 <Field label="End Time" required error={errors.endTime}><DecorationTimePicker value={values.endTime} disabled={busy} onChange={value=>set('endTime',value)}/></Field>
 <Field label="Package Rate (optional)" error={errors.packageRate}><DecorationMoneyInput disabled={busy} placeholder="Finalized during decoration selection" className={input} value={values.packageRate} onValueChange={value=>set('packageRate',value)}/></Field></div>
 <Field label="Event Address (optional)"><input disabled={busy} className={input} value={values.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="Notes"><textarea disabled={busy} className={`${input} min-h-28 resize-y`} value={values.notes} onChange={e=>set('notes',e.target.value)}/></Field><div className="flex flex-col-reverse gap-3 sm:flex-row sm:flex-wrap sm:justify-end"><button type="button" disabled={busy} onClick={requestClose} className="rounded-2xl border border-slate-200 px-5 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-50">Cancel</button><button type="submit" disabled={busy||optionsLoading} className="rounded-2xl bg-amber-400 px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-amber-500 disabled:opacity-60">{busy?'Saving…':booking?'Save changes':'Create Inquiry'}</button>{!booking?<button type="button" disabled={busy||optionsLoading} onClick={()=>void submitIntent('CONFIRMED')} className="rounded-2xl bg-emerald-500 px-5 py-3 text-sm font-semibold text-white hover:bg-emerald-600 disabled:opacity-60">Confirm Booking</button>:null}</div></form></div></div>{pendingConfirmation?<DecorationConfirmationModal draft={pendingConfirmation} onClose={()=>setPendingConfirmation(current=>current?cancelDecorationConfirmationDraft(current):null)} onSubmitDraft={async confirmation=>{if(!accessToken)throw new Error('Session is unavailable');const result=await submitDecorationConfirmationDraft(pendingConfirmation,confirmation,payload=>createConfirmedDecorationBooking(accessToken,payload));return result.booking}} onConfirmed={confirmed=>{setPendingConfirmation(null);onSaved(confirmed)}}/>:null}</BodyPortal>
}
