'use client';

import { useCallback, useEffect, useMemo, useRef, useState, type ComponentType, type RefObject } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { BodyPortal } from '@/components/ui/body-portal';
import { useModalViewport } from '@/components/ui/use-modal-viewport';
import { DecorationImageCropModal } from './decoration-image-crop-modal';
import { DecorationNoteBlockEditor } from './decoration-note-block-editor';
import { DecorationGeneralNotes } from './decoration-general-notes';
import { useDecorationNotesAutosave } from './use-decoration-notes-autosave';
import { deleteDecorationSelectionDraft, fetchDecorationAvailability, fetchDecorationCategories, fetchDecorationItems, fetchDecorationSelectionDraft, saveDecorationSelection, saveDecorationSelectionDraft, uploadCustomDecorationImage } from '@/lib/auth/api';
import type { DecorationBooking, DecorationItem } from '@/lib/auth/types';
import { addCustomNoteBlock, buildDecorationDraftPayload, buildDecorationFinalPayload, hydrateDecorationNotes, linkCatalogItem, moveDecorationNoteBlock, removeDecorationNoteBlock, updateDecorationNoteBlock, validateDecorationNotesForFinalSave, type DecorationNotesState } from '@/lib/decoration/notes-builder-state';
import { materializeDecorationImageFile, validateDecorationImageFile } from '@/lib/decoration/catalog-images';
import { applyDecorationAvailability } from '@/lib/decoration/availability';
import { decorationReservationErrorMessage } from '@/lib/decoration/reservation-error';
import { validateDecorationSelectionPrice } from '@/lib/decoration/selection-price';

export type CustomCropModalProps={file:File;busy?:boolean;onCancel:()=>void;onConfirm:(file:File)=>void|Promise<void>;returnFocusRef?:RefObject<HTMLElement|null>};
type Props={booking:DecorationBooking;onClose:()=>void;onSaved:(booking:DecorationBooking)=>void;accessToken?:string|null;loadCategories?:typeof fetchDecorationCategories;loadItems?:typeof fetchDecorationItems;loadAvailability?:typeof fetchDecorationAvailability;uploadCustomImage?:typeof uploadCustomDecorationImage;materializeImage?:typeof materializeDecorationImageFile;CropModal?:ComponentType<CustomCropModalProps>};

export function DecorationSelectionModal(props:Props){const auth=useAuth();return <DecorationSelectionModalContent {...props} loadAvailability={props.loadAvailability??fetchDecorationAvailability} accessToken={props.accessToken===undefined?auth.accessToken:props.accessToken}/>;}

export function DecorationSelectionModalContent({booking,onClose,onSaved,accessToken,loadCategories=fetchDecorationCategories,loadItems=fetchDecorationItems,loadAvailability,uploadCustomImage=uploadCustomDecorationImage,materializeImage=materializeDecorationImageFile,CropModal=DecorationImageCropModal}:Props){
 const [state,setState]=useState<DecorationNotesState>(()=>hydrateDecorationNotes(booking.decorationSnapshot??[],null)),[items,setItems]=useState<DecorationItem[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[validation,setValidation]=useState({blocks:{} as Record<string,string[]>,generalNotes:null as string|null}),[changed,setChanged]=useState(0),[pending,setPending]=useState<File|null>(null);
 const trigger=useRef<HTMLButtonElement>(null),input=useRef<HTMLInputElement>(null);useModalViewport(onClose, saving || uploading);
 useEffect(()=>{if(!accessToken)return;const abort=new AbortController();setLoading(true);Promise.all([loadCategories(accessToken),loadItems(accessToken),loadAvailability?.(accessToken,booking.id),fetchDecorationSelectionDraft(accessToken,booking.id,abort.signal)]).then(([,catalog,availability,draft])=>{if(abort.signal.aborted)return;setItems(applyDecorationAvailability(catalog,availability));setState(hydrateDecorationNotes(booking.decorationSnapshot??[],draft));}).catch(reason=>{if(!abort.signal.aborted)setError(reason instanceof Error?reason.message:'Unable to load decoration notes.');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[accessToken,booking.id,booking.decorationSnapshot,loadAvailability,loadCategories,loadItems]);
 const draft=useMemo(()=>changed?buildDecorationDraftPayload(state):null,[changed,state]);
 const saveDraft=useCallback((payload:ReturnType<typeof buildDecorationDraftPayload>,signal:AbortSignal)=>saveDecorationSelectionDraft(accessToken!,booking.id,payload,signal),[accessToken,booking.id]);
 const discardDraft=useCallback(async()=>{if(accessToken)await deleteDecorationSelectionDraft(accessToken,booking.id);setState(hydrateDecorationNotes(booking.decorationSnapshot??[],null));setChanged(0);},[accessToken,booking.decorationSnapshot,booking.id]);
 const autosave=useDecorationNotesAutosave({draft,enabled:!!accessToken&&!loading,save:saveDraft,discardDraft});
 const change=(next:(current:DecorationNotesState)=>DecorationNotesState)=>{setState(next);setChanged(value=>value+1);};
 async function source(file:File){const message=validateDecorationImageFile(file,0);if(message){setError(message);return;}try{setPending(await materializeImage(file));}catch(reason){setError(reason instanceof Error?reason.message:'Unable to read image.');}}
 async function upload(file:File){if(!accessToken)return;setUploading(true);try{const stable=await materializeImage(file),image=await uploadCustomImage(accessToken,booking.id,stable);change(current=>addCustomNoteBlock(current,image));setPending(null);}catch(reason){setError(reason instanceof Error?reason.message:'Unable to upload image.');}finally{setUploading(false);}}
 async function finalSave(){if(!accessToken)return;const errors=validateDecorationNotesForFinalSave(state),priceError=validateDecorationSelectionPrice(state.finalPackagePrice,booking.totalCollected);setValidation(errors);if(Object.keys(errors.blocks).length||errors.generalNotes||priceError){setError(priceError??'Correct the highlighted note details.');return;}if(!state.blocks.length){setError('Add at least one photo note.');return;}setSaving(true);try{await autosave.flush();const payload=buildDecorationFinalPayload(state);const result=await saveDecorationSelection(accessToken,booking.id,payload.items,payload.finalPackagePrice,payload.customItems,payload.generalNotes);onSaved(result.booking);}catch(reason){setError(decorationReservationErrorMessage(reason));}finally{setSaving(false);}}
 return <BodyPortal><div className="fixed inset-0 z-[75] flex items-end justify-center overflow-x-hidden bg-slate-950/55 sm:items-center sm:p-5" role="dialog" aria-modal="true"><div className="flex h-[100dvh] w-full max-w-5xl flex-col overflow-hidden rounded-t-3xl bg-slate-50 sm:h-[calc(100dvh-2.5rem)] sm:rounded-3xl"><header className="flex shrink-0 justify-between border-b bg-white p-4 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Decoration Notes Builder</p><h2 className="text-xl font-bold text-slate-950">{booking.customer.name}</h2><p className="text-sm text-slate-600">{autosave.status==='saving'?'Saving draft…':autosave.status==='saved'?'Draft saved':autosave.status==='error'?'Draft not saved':'Add photo-based decoration instructions'}</p></div><button aria-label="Close Decoration Selection" disabled={saving||uploading} onClick={onClose} className="h-11 w-11 rounded-full border bg-white text-2xl text-slate-600">×</button></header>
 <main className="min-h-0 flex-1 space-y-4 overflow-y-auto overflow-x-hidden p-4 sm:p-6">{error||autosave.error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error||autosave.error}{autosave.status==='error'?<button onClick={()=>void autosave.retry()} className="ml-3 font-bold underline">Retry</button>:null}</div>:null}{loading?<p className="py-20 text-center text-slate-600">Loading decoration notes…</p>:<>{state.blocks.map((block,index)=><DecorationNoteBlockEditor key={block.clientId} block={block} index={index} count={state.blocks.length} items={items} errors={validation.blocks[block.clientId]} disabled={saving} onChange={patch=>change(current=>updateDecorationNoteBlock(current,block.clientId,patch))} onLink={item=>change(current=>linkCatalogItem(current,block.clientId,item))} onMove={direction=>change(current=>moveDecorationNoteBlock(current,block.clientId,direction))} onRemove={()=>change(current=>removeDecorationNoteBlock(current,block.clientId))}/>)}<button ref={trigger} onClick={()=>input.current?.click()} disabled={uploading} className="min-h-28 w-full rounded-2xl border-2 border-dashed border-slate-300 bg-white font-bold text-slate-800">{uploading?'Uploading photo…':'+ Add Photo Note'}</button><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void source(file);}}/><DecorationGeneralNotes value={state.generalNotes} disabled={saving} error={validation.generalNotes} onChange={value=>change(current=>({...current,generalNotes:value}))}/></>}</main>
 <footer className="safe-pad-bottom shrink-0 border-t bg-white/95 p-3 sm:p-4"><div className="grid gap-3 sm:grid-cols-[1fr_auto_auto] sm:items-end"><label className="text-sm font-semibold text-slate-700">Final Package Price<input type="number" min="0" value={state.finalPackagePrice} onChange={event=>change(current=>({...current,finalPackagePrice:event.target.value}))} className="light-form-field mt-1 min-h-11 w-full rounded-xl border bg-white px-3 text-slate-950"/></label><button disabled={!changed||saving} onClick={()=>{if(confirm('Discard saved draft and restore the finalized selection?'))void autosave.discard();}} className="rounded-xl border px-5 py-3 font-bold text-red-600">Discard Draft</button><button disabled={loading||saving||uploading} onClick={()=>void finalSave()} className="rounded-xl bg-amber-500 px-6 py-3 font-bold text-slate-950">{saving?'Saving…':`Save ${state.blocks.length} notes`}</button></div></footer></div></div>{pending?<CropModal file={pending} busy={uploading} returnFocusRef={trigger} onCancel={()=>setPending(null)} onConfirm={upload}/>:null}</BodyPortal>;
}
