'use client';
import { FormEvent, useState } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { addDecorationFollowup } from '@/lib/auth/api';
import type { DecorationBooking } from '@/lib/auth/types';
import { buildDecorationFollowupPayload, type DecorationFollowupForm, validateDecorationFollowupForm } from '@/lib/decoration/followup-form';
const input='mt-1 w-full rounded-xl border border-slate-300 px-4 py-3 text-base outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100';
export function DecorationFollowupModal({booking,onClose,onSaved}:{booking:DecorationBooking;onClose:()=>void;onSaved:(booking:DecorationBooking)=>void}){const{accessToken}=useAuth();const today=new Date().toLocaleDateString('en-CA');const[form,setForm]=useState<DecorationFollowupForm>({date:today,nextDate:'',note:''}),[errors,setErrors]=useState<Partial<Record<keyof DecorationFollowupForm,string>>>({}),[error,setError]=useState(''),[saving,setSaving]=useState(false);async function submit(event:FormEvent){event.preventDefault();if(!accessToken||saving)return;const next=validateDecorationFollowupForm(form);setErrors(next);if(Object.keys(next).length)return;setSaving(true);setError('');try{onSaved(await addDecorationFollowup(accessToken,booking.id,buildDecorationFollowupPayload(form)))}catch(reason){setError(reason instanceof Error?reason.message:'Unable to add follow-up.')}finally{setSaving(false)}}return <div className="fixed inset-0 z-[72] flex items-end justify-center bg-slate-950/50 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="followup-title" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}}><div className="w-full rounded-t-3xl bg-white p-5 shadow-2xl sm:max-w-xl sm:rounded-3xl sm:p-7"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">{booking.bookingNumber}</p><h2 id="followup-title" className="text-2xl font-bold">Add Follow-up</h2></div><button disabled={saving} onClick={onClose} aria-label="Close Add Follow-up" className="h-11 w-11 rounded-full border text-2xl text-slate-500">×</button></div>{error?<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<form onSubmit={submit} className="mt-5 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Follow-up date" error={errors.date}><input autoFocus type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className={input}/></Field><Field label="Next follow-up (optional)" error={errors.nextDate}><input type="date" value={form.nextDate} onChange={e=>setForm({...form,nextDate:e.target.value})} className={input}/></Field></div><Field label="Note" error={errors.note}><textarea rows={4} maxLength={1000} value={form.note} onChange={e=>setForm({...form,note:e.target.value})} className={input}/></Field><button disabled={saving} className="w-full rounded-xl bg-amber-500 p-3.5 font-bold text-slate-950 disabled:opacity-50">{saving?'Saving follow-up…':'Save Follow-up'}</button></form></div></div>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-semibold text-slate-700">{label}{children}{error?<span className="mt-1 block text-xs font-normal text-red-600">{error}</span>:null}</label>}
