import type { DecorationItem } from '@/lib/auth/types';
import type { DecorationChoice } from '@/lib/decoration/selection-state';

const controlClassName = 'decoration-light-field mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-slate-950 placeholder:text-slate-400 disabled:bg-slate-100 disabled:text-slate-500';

export function DecorationSelectionItemCard({ item, choice, error, disabled, onToggle, onChange }: { item: DecorationItem; choice?: DecorationChoice; error?: string; disabled: boolean; onToggle: () => void; onChange: (patch: Partial<DecorationChoice>) => void }) {
  const image = item.images.find((entry) => entry.id === choice?.imageId) ?? item.images.find((entry) => entry.isCover) ?? item.images[0];
  const unavailable = item.availableQuantity < 1;
  return <article className={`overflow-hidden rounded-2xl border ${unavailable ? 'border-red-300 bg-red-50' : 'bg-white'} ${choice ? 'border-amber-400 ring-2 ring-amber-100' : !unavailable ? 'border-slate-200' : ''}`}>
    <button type="button" disabled={disabled || (unavailable && !choice)} onClick={onToggle} className="w-full text-left disabled:cursor-not-allowed disabled:opacity-70">
      <div className={`aspect-[16/10] ${unavailable ? 'bg-red-100 grayscale' : 'bg-slate-100'}`}>{image ? <img src={image.url} alt={item.name} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-sm text-slate-400">No image</div>}</div>
      <div className="flex items-start justify-between gap-3 p-4"><div><h3 className="font-bold text-slate-950">{item.name}</h3><p className={`text-xs font-semibold ${unavailable ? 'text-red-700' : 'text-emerald-700'}`}>{unavailable ? 'Not available for this event' : `${item.availableQuantity} available for this event`}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${unavailable ? 'bg-red-100 text-red-700' : choice ? 'bg-amber-100 text-amber-800' : 'bg-slate-100 text-slate-600'}`}>{unavailable ? 'Unavailable' : choice ? 'Selected' : 'Select'}</span></div>
    </button>
    {choice ? <div className="space-y-3 border-t border-slate-100 p-4"><label className="block text-xs font-semibold text-slate-600">Quantity<input type="number" inputMode="numeric" min="1" max={item.availableQuantity} disabled={disabled} value={choice.quantity} onChange={(event) => onChange({ quantity: Number(event.target.value) })} className={`${controlClassName} text-base`} /></label>{item.images.length > 1 ? <label className="block text-xs font-semibold text-slate-600">Image<select value={choice.imageId ?? ''} disabled={disabled} onChange={(event) => onChange({ imageId: event.target.value })} className={`${controlClassName} text-sm`}>{item.images.map((entry, index) => <option key={entry.id} value={entry.id}>Image {index + 1}{entry.isCover ? ' (cover)' : ''}</option>)}</select></label> : null}<label className="block text-xs font-semibold text-slate-600">Description (optional)<textarea rows={2} maxLength={500} disabled={disabled} value={choice.description} onChange={(event) => onChange({ description: event.target.value })} className={`${controlClassName} text-sm`} /></label>{error ? <p className="text-xs font-semibold text-red-600">{error}</p> : null}</div> : null}
  </article>;
}
