'use client';
import { useEffect, useState } from 'react';
import { generateBookingFeedbackLink, getBookingFeedbackState, updateBookingFeedbackNote } from '@/lib/booking-feedback/api';
import type { BookingFeedbackState } from '@/lib/booking-feedback/types';

type Props = { accessToken: string; orderId: string; customerName: string; onClose: () => void };
export function BookingFeedbackModal({ accessToken, orderId, customerName, onClose }: Props) {
  const [state, setState] = useState<BookingFeedbackState | null>(null);
  const [link, setLink] = useState(''); const [note, setNote] = useState('');
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { getBookingFeedbackState(accessToken, orderId).then((value) => { setState(value); setNote(value.response?.internalNote ?? ''); }).catch((reason) => setMessage(reason instanceof Error ? reason.message : 'Unable to load feedback.')); }, [accessToken, orderId]);
  async function generate(regenerate = false) { setBusy(true); setMessage(''); try { const result = await generateBookingFeedbackLink(accessToken, orderId, regenerate); setLink(result.link); setState(await getBookingFeedbackState(accessToken, orderId)); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Unable to create link.'); } finally { setBusy(false); } }
  async function copyLink() { await navigator.clipboard.writeText(link); setMessage('Feedback link copied.'); }
  async function saveNote() { setBusy(true); try { await updateBookingFeedbackNote(accessToken, orderId, note); setMessage('Internal note saved.'); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Unable to save note.'); } finally { setBusy(false); } }
  function confirmRegenerate() { if (window.confirm('Generate a new link? The previously shared feedback link will stop working immediately.')) void generate(true); }
  return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/55 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[92dvh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:max-w-2xl sm:rounded-3xl sm:p-7">
    <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-600">Booking feedback</p><h2 className="mt-2 text-2xl font-bold text-slate-950">{customerName}</h2></div><button onClick={onClose} className="h-11 w-11 rounded-full border text-xl text-slate-600" aria-label="Close">×</button></div>
    {!state ? <p className="mt-8 text-sm text-slate-500">Loading feedback status…</p> : state.state === 'SUBMITTED' && state.response ? <><div className="mt-6 rounded-2xl bg-emerald-50 p-5"><p className="text-sm font-semibold text-emerald-800">Feedback received</p><p className="mt-1 text-3xl font-black text-emerald-950">{state.response.averageRating.toFixed(1)} / 5</p></div><div className="mt-4 space-y-3">{state.response.answers.map((answer) => <div key={answer.questionId} className="rounded-xl border p-4"><p className="text-sm text-slate-700">{answer.questionText}</p><p className="mt-1 font-bold text-amber-600">{'★'.repeat(answer.rating)}{'☆'.repeat(5 - answer.rating)}</p></div>)}</div>{state.response.comment ? <div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm">{state.response.comment}</div> : null}<label className="mt-5 block text-sm font-semibold">Internal note<textarea value={note} onChange={(e) => setNote(e.target.value)} className="mt-2 min-h-24 w-full rounded-xl border p-3 font-normal"/></label><button disabled={busy} onClick={saveNote} className="mt-3 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Save note</button></> : <><div className="mt-6 rounded-2xl border p-5"><p className="font-semibold">{state.state === 'PENDING' ? 'Waiting for customer response' : 'No feedback link generated yet'}</p><p className="mt-1 text-sm text-slate-500">{state.state === 'PENDING' ? 'For security, an existing link cannot be displayed again. Regenerate only if the customer needs a replacement.' : 'Generate a secure, single-use link and share it with the customer.'}</p></div>{link ? <div className="mt-4 flex gap-2"><input readOnly value={link} className="min-w-0 flex-1 rounded-xl border px-3 text-sm"/><button onClick={copyLink} className="rounded-xl bg-amber-400 px-4 py-3 font-bold">Copy</button></div> : null}<div className="mt-4">{state.state === 'PENDING' ? <button disabled={busy} onClick={confirmRegenerate} className="rounded-xl border border-red-200 px-5 py-3 text-sm font-bold text-red-700">Generate replacement link</button> : <button disabled={busy} onClick={() => generate(false)} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Generate link</button>}</div></>}
    {message ? <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm font-medium text-amber-800">{message}</p> : null}
  </div></div>;
}
