'use client';

import { DragEvent, useMemo, useRef, useState } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { confirmDecorationImport, downloadDecorationImportTemplate, previewDecorationImport } from '@/lib/auth/api';
import { hasPermission, PERMISSIONS } from '@/lib/auth/permissions';
import type { DecorationImportConfirmation, DecorationImportPreview } from '@/lib/auth/types';
import { filterImportRows, ImportRowFilter, validateImportFile } from '@/lib/decoration/import-view';

function saveBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=filename;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url)}

export default function Page(){
 const{accessToken,user}=useAuth(),inputRef=useRef<HTMLInputElement>(null);const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<DecorationImportPreview|null>(null),[result,setResult]=useState<DecorationImportConfirmation|null>(null),[filter,setFilter]=useState<ImportRowFilter>('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[dragging,setDragging]=useState(false),[confirmOpen,setConfirmOpen]=useState(false),[createConfiguration,setCreateConfiguration]=useState(false);const canCreateConfiguration=user?.role==='company_admin'||hasPermission(user,PERMISSIONS.DECORATION_CONFIGURATION_MANAGE);const shown=useMemo(()=>filterImportRows(preview?.rows??[],filter),[preview,filter]);
 function choose(next:File|null){if(!next)return;const issue=validateImportFile(next);if(issue){setError(issue);return}setFile(next);setPreview(null);setResult(null);setError('');setProgress(0)}
 async function download(format:'xlsx'|'csv'){if(!accessToken)return;try{setBusy(true);setError('');saveBlob(await downloadDecorationImportTemplate(accessToken,format),`decoration-booking-import-v1.0.${format}`)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to download template.')}finally{setBusy(false)}}
 async function upload(){if(!accessToken||!file)return;try{setBusy(true);setError('');setProgress(0);const data=await previewDecorationImport(accessToken,file,setProgress);setPreview(data);setFilter(data.invalidRows?'invalid':'all')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to preview file.')}finally{setBusy(false)}}
 async function confirm(){if(!accessToken||!preview)return;try{setBusy(true);setError('');setResult(await confirmDecorationImport(accessToken,preview.jobId,createConfiguration));setConfirmOpen(false)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to confirm import.')}finally{setBusy(false)}}
 function reset(){setFile(null);setPreview(null);setResult(null);setFilter('all');setError('');setProgress(0);setCreateConfiguration(false);if(inputRef.current)inputRef.current.value=''}
 function drop(event:DragEvent<HTMLDivElement>){event.preventDefault();setDragging(false);choose(event.dataTransfer.files[0]??null)}
 return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-600">Data migration</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Import decoration bookings</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Download the template, add legacy Excel records, preview every row, then explicitly confirm. Previewing never creates bookings.</p></header>
 <section className="grid gap-4 lg:grid-cols-[1fr_1.4fr]"><div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">1. Download a template</h2><p className="mt-1 text-sm text-slate-500">Use the exact columns and date formats supplied.</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void download('xlsx')} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Download Excel</button><button disabled={busy} onClick={()=>void download('csv')} className="rounded-xl border px-4 py-2.5 text-sm font-semibold disabled:opacity-50">Download CSV</button></div></div>
 <div className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">2. Select completed file</h2><div onDragEnter={()=>setDragging(true)} onDragLeave={()=>setDragging(false)} onDragOver={event=>event.preventDefault()} onDrop={drop} className={`mt-3 rounded-2xl border-2 border-dashed p-6 text-center transition ${dragging?'border-amber-500 bg-amber-50':'border-slate-300'}`}><input ref={inputRef} type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={event=>choose(event.target.files?.[0]??null)}/><p className="font-semibold">{file?file.name:'Drop CSV/XLSX here'}</p><p className="mt-1 text-xs text-slate-500">Maximum 5 MB and 2,000 data rows</p><button type="button" onClick={()=>inputRef.current?.click()} className="mt-3 rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Choose file</button></div>{file&&<button disabled={busy} onClick={()=>void upload()} className="mt-3 w-full rounded-xl bg-amber-500 px-4 py-3 font-semibold text-white disabled:opacity-50">{busy?`Uploading ${progress}%`:'Upload and preview'}</button>}{busy&&file&&<div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-amber-500 transition-all" style={{width:`${progress}%`}}/></div>}</div></section>
 {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 {result?<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center"><h2 className="text-2xl font-bold text-emerald-900">Import completed</h2><p className="mt-2 text-emerald-800">{result.importedRows} bookings imported · {result.skippedRows} rows skipped{result.reused?' · Existing result returned':''}</p><button onClick={reset} className="mt-5 rounded-xl bg-emerald-700 px-5 py-3 font-semibold text-white">Import another file</button></section>:preview&&<><section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{label:'Total',value:preview.totalRows,color:'text-slate-700'},{label:'Valid',value:preview.validRows,color:'text-emerald-700'},{label:'Invalid',value:preview.invalidRows,color:'text-red-700'},{label:'Warnings',value:preview.warningRows,color:'text-amber-700'}].map(item=><div key={item.label} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase text-slate-400">{item.label}</p><p className={`mt-1 text-2xl font-bold ${item.color}`}>{item.value}</p></div>)}</section>
 <section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">3. Review preview</h2><p className="text-xs text-slate-500">Job {preview.jobId}{preview.reused?' · Reused preview':''}</p></div><div className="flex flex-wrap gap-2">{(['all','valid','invalid','warning'] as ImportRowFilter[]).map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-full px-3 py-1.5 text-xs font-semibold capitalize ${filter===item?'bg-slate-900 text-white':'bg-slate-100 text-slate-600'}`}>{item}</button>)}</div></div><div className="max-h-[34rem] overflow-auto"><div className="divide-y lg:hidden">{shown.map(row=><article key={row.rowNumber} className="space-y-2 p-4"><div className="flex justify-between"><b>Row {row.rowNumber}</b><span className={`rounded-full px-2 py-1 text-xs ${row.isValid?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{row.isValid?'Valid':'Invalid'}</span></div><p className="text-sm">{String(row.normalized.customerName??'')} · {String(row.normalized.mobile??'')}</p><p className="text-xs text-slate-500">{String(row.normalized.eventDate??'')} · {String(row.normalized.venueName??'')}</p>{row.errors.map(message=><p key={message} className="text-xs text-red-600">{message}</p>)}{row.warnings.map(message=><p key={message} className="text-xs text-amber-700">{message}</p>)}</article>)}</div><table className="hidden min-w-full text-left text-sm lg:table"><thead className="sticky top-0 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Row</th><th className="p-3">Customer</th><th className="p-3">Date / Event</th><th className="p-3">Venue</th><th className="p-3">Result</th></tr></thead><tbody className="divide-y">{shown.map(row=><tr key={row.rowNumber} className="align-top"><td className="p-3 font-semibold">{row.rowNumber}</td><td className="p-3">{String(row.normalized.customerName??'')}<br/><span className="text-xs text-slate-500">{String(row.normalized.mobile??'')}</span></td><td className="p-3">{String(row.normalized.eventDate??'')}<br/><span className="text-xs text-slate-500">{String(row.normalized.functionName??'')}</span></td><td className="p-3">{String(row.normalized.venueName??'')}<br/><span className="text-xs text-slate-500">{String(row.normalized.hallName??'')}</span></td><td className="max-w-md p-3">{row.isValid?<span className="text-emerald-700">Ready</span>:row.errors.map(message=><p key={message} className="text-xs text-red-600">{message}</p>)}{row.warnings.map(message=><p key={message} className="text-xs text-amber-700">{message}</p>)}</td></tr>)}</tbody></table>{shown.length===0&&<p className="p-8 text-center text-sm text-slate-500">No rows match this filter.</p>}</div></section>
 <div className="sticky bottom-3 flex flex-col gap-3 rounded-2xl border bg-white/95 p-4 shadow-xl backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{preview.validRows} rows are ready now</p><p className="text-xs text-slate-500">Authorized users can create missing configuration during confirmation; other invalid rows remain skipped.</p></div><div className="flex gap-2"><button onClick={reset} className="rounded-xl border px-4 py-2.5 font-semibold">Start over</button><button disabled={(!preview.validRows&&!(canCreateConfiguration&&preview.configurationActions.length))||busy} onClick={()=>setConfirmOpen(true)} className="rounded-xl bg-emerald-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">Confirm import</button></div></div></>}
 {confirmOpen&&preview&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold">Confirm {preview.validRows} bookings?</h2><p className="mt-2 text-sm text-slate-500">This creates bookings permanently. Repeating confirmation will not create duplicates.</p>{preview.configurationActions.length>0&&<div className="mt-4 rounded-xl bg-amber-50 p-4"><p className="font-semibold text-amber-900">{preview.configurationActions.length} missing configuration items</p>{canCreateConfiguration?<label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={createConfiguration} onChange={event=>setCreateConfiguration(event.target.checked)}/><span>Create missing event types, venues and halls during confirmation</span></label>:<p className="mt-2 text-sm text-amber-800">You need configuration-management permission to create them. Those rows will remain skipped.</p>}</div>}<div className="mt-6 flex justify-end gap-2"><button disabled={busy} onClick={()=>setConfirmOpen(false)} className="rounded-xl border px-4 py-2.5">Cancel</button><button disabled={busy} onClick={()=>void confirm()} className="rounded-xl bg-emerald-600 px-4 py-2.5 font-semibold text-white">{busy?'Importing…':'Confirm import'}</button></div></div></div>}
 </main>
}
