'use client';
import { useEffect, useState } from 'react';
import { submitPublicBookingFeedback, validatePublicBookingFeedback } from '@/lib/booking-feedback/api';
import { buildBookingFeedbackAnswers } from '@/lib/booking-feedback/domain';
import type { PublicBookingFeedback } from '@/lib/booking-feedback/types';

export default function BookingFeedbackPage() {
  const [token, setToken] = useState(''); const [data, setData] = useState<PublicBookingFeedback | null>(null);
  const [ratings, setRatings] = useState<Record<string, number>>({}); const [comment, setComment] = useState('');
  const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { const url = new URL(window.location.href); const value = url.searchParams.get('token') || sessionStorage.getItem('booking_feedback_token') || ''; if (value) { sessionStorage.setItem('booking_feedback_token', value); url.searchParams.delete('token'); window.history.replaceState({}, '', `${url.pathname}${url.search}${url.hash}`); } setToken(value); if (value) validatePublicBookingFeedback(value).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : 'Invalid feedback link.')); }, []);
  if (!token || error || (data && data.status !== 'READY')) return <main className="grid min-h-dvh place-items-center bg-slate-50 p-5"><div className="w-full max-w-xl rounded-3xl bg-white p-8 text-center shadow-xl"><h1 className="text-3xl font-bold text-slate-950">{data?.status === 'SUBMITTED' ? 'Thank you' : 'Invalid feedback link'}</h1><p className="mt-3 text-slate-500">{data?.status === 'SUBMITTED' ? 'Your feedback has already been received.' : error || 'Please use the exact link shared with you.'}</p></div></main>;
  if (!data) return <main className="grid min-h-dvh place-items-center">Loading…</main>;
  async function submit() { let answers; try { answers = buildBookingFeedbackAnswers(data?.questions ?? [], ratings); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Please answer at least one question.'); return; } if (!confirmed) { setError('Please confirm that this feedback is yours.'); return; } setBusy(true); setError(''); try { await submitPublicBookingFeedback(token, { answers, comment: comment.trim() || undefined, confirmed: true }); sessionStorage.removeItem('booking_feedback_token'); setData({ status: 'SUBMITTED' }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to submit feedback.'); } finally { setBusy(false); } }
  return <main className="min-h-dvh bg-[linear-gradient(135deg,#fffaf0,#f8fafc)] px-4 py-8 sm:py-14"><div className="mx-auto max-w-2xl rounded-3xl bg-white p-5 shadow-2xl sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.22em] text-amber-600">{data.branding?.name || 'Banquet feedback'}</p><h1 className="mt-3 text-3xl font-black text-slate-950 sm:text-4xl">Tell us about your event</h1><p className="mt-2 text-slate-500">{data.booking?.customerName} · {data.booking?.eventType}</p><p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm font-medium text-amber-800">Questions are optional—please rate at least one.</p><div className="mt-5 space-y-4">{data.questions?.map((question, index) => <section key={question.id} className="rounded-2xl border border-slate-200 p-5"><p className="font-semibold text-slate-900"><span className="mr-2 text-amber-600">{index + 1}.</span>{question.text}</p><div className="mt-4 flex justify-between gap-1 sm:justify-start">{[1,2,3,4,5].map((star) => <button key={star} onClick={() => setRatings((values) => ({ ...values, [question.id]: star }))} className={`h-12 w-12 rounded-xl text-2xl ${star <= (ratings[question.id] || 0) ? 'bg-amber-100 text-amber-500' : 'bg-slate-50 text-slate-300'}`} aria-label={`${star} stars`}>★</button>)}</div>{ratings[question.id] ? <button type="button" onClick={() => setRatings((values) => { const next = { ...values }; delete next[question.id]; return next; })} className="mt-2 text-xs font-semibold text-slate-500 underline">Clear this answer</button> : null}</section>)}</div><label className="mt-5 block font-semibold text-slate-700">Anything else you would like to share?<textarea value={comment} onChange={(event) => setComment(event.target.value)} className="mt-2 min-h-28 w-full rounded-2xl border border-slate-200 p-4 font-normal"/></label><label className="mt-5 flex items-start gap-3 text-sm text-slate-600"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} className="mt-1 h-5 w-5"/>I confirm this feedback is based on my event experience.</label>{error ? <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}<button onClick={submit} disabled={busy} className="mt-6 w-full rounded-2xl bg-amber-400 px-5 py-4 font-bold text-slate-950 disabled:opacity-50">{busy ? 'Submitting…' : 'Submit feedback'}</button></div></main>;
}
