'use client';

import { useEffect, useState } from 'react';
import { CommonModal } from '@/components/ui/common-modal';
import type { CustomerFeedback, FeedbackImageDisplayMode } from '@/lib/feedback/types';
import { FeedbackImageEditor } from './feedback-image-editor';

export type FeedbackReviewAction = 'save' | 'replace-image' | 'approve' | 'approve-publish' | 'reject' | 'publish' | 'unpublish' | 'archive';
export type FeedbackReviewPayload = { publicVersion?: CustomerFeedback['publicVersion']; displayOrder?: number; image?: File; displayMode?: FeedbackImageDisplayMode };

export function FeedbackReviewModal({ record, onClose, onAction }: { record: CustomerFeedback; onClose: () => void; onAction: (action: FeedbackReviewAction, record: CustomerFeedback, payload?: FeedbackReviewPayload) => void | Promise<void> }) {
  const [publicVersion, setPublicVersion] = useState(record.publicVersion);
  const [displayOrder, setDisplayOrder] = useState(record.displayOrder);
  const [replacementImage, setReplacementImage] = useState<File | null>(null);
  const [replacementMode, setReplacementMode] = useState<FeedbackImageDisplayMode>(record.publicVersion.image.displayMode);
  useEffect(() => {
    setPublicVersion(record.publicVersion);
    setDisplayOrder(record.displayOrder);
    setReplacementImage(null);
    setReplacementMode(record.publicVersion.image.displayMode);
  }, [record]);
  const input = 'w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-semibold text-slate-950 outline-none focus:border-amber-400';
  const version = (title: string, value: CustomerFeedback['original'], editable: boolean) => <section className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-[10px] font-black uppercase tracking-[.18em] text-amber-700">{title}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Name<input readOnly={!editable} className={`${input} mt-1`} value={value.fullName} onChange={editable ? (e) => setPublicVersion((current) => ({ ...current, fullName: e.target.value })) : undefined} /></label><label className="text-xs font-bold text-slate-600">Designation<input readOnly={!editable} className={`${input} mt-1`} value={value.designation} onChange={editable ? (e) => setPublicVersion((current) => ({ ...current, designation: e.target.value })) : undefined} /></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Company<input readOnly={!editable} className={`${input} mt-1`} value={value.company} onChange={editable ? (e) => setPublicVersion((current) => ({ ...current, company: e.target.value })) : undefined} /></label><label className="text-xs font-bold text-slate-600">Rating<input readOnly={!editable} type="number" min={1} max={5} className={`${input} mt-1`} value={value.rating} onChange={editable ? (e) => setPublicVersion((current) => ({ ...current, rating: Number(e.target.value) })) : undefined} /></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Message<textarea readOnly={!editable} rows={5} className={`${input} mt-1 resize-y`} value={value.message} onChange={editable ? (e) => setPublicVersion((current) => ({ ...current, message: e.target.value })) : undefined} /></label></div><div className="mt-3 h-52 overflow-hidden rounded-xl bg-slate-100"><img alt={`${title} customer`} src={value.image.url} className={`h-full w-full ${value.image.displayMode === 'FULL' ? 'object-contain' : 'object-cover'}`} /></div></section>;
  return <CommonModal title={`Review ${record.publicVersion.fullName}`} description="The original submission is immutable. Edit only the public version shown on the landing page." onClose={onClose} widthClassName="max-w-6xl" mobileFullScreen>
    <div className="grid gap-4 lg:grid-cols-2">{version('Original submission', record.original, false)}{version('Public version', publicVersion, true)}</div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[180px_1fr]"><label className="rounded-2xl border border-slate-200 bg-white p-4 text-xs font-bold text-slate-600">Display order<input type="number" min={0} value={displayOrder} onChange={(event) => setDisplayOrder(Number(event.target.value))} className={`${input} mt-2`} /></label><details className="rounded-2xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer font-bold text-slate-900">Replace public photo</summary><div className="mt-4"><FeedbackImageEditor file={replacementImage} displayMode={replacementMode} onChange={(file, mode) => { setReplacementImage(file); setReplacementMode(mode); }} />{replacementImage ? <button type="button" onClick={() => onAction('replace-image', record, { image: replacementImage, displayMode: replacementMode })} className="mt-3 w-full rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Save public photo</button> : null}</div></details></div>
    <div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={() => onAction('save', record, { publicVersion, displayOrder })} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold text-slate-700">Save public version</button>{record.moderationStatus === 'SUBMITTED' ? <><button type="button" onClick={() => onAction('reject', record)} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700">Reject</button><button type="button" onClick={() => onAction('approve', record)} className="rounded-xl border border-emerald-300 px-4 py-2.5 text-sm font-bold text-emerald-700">Approve</button><button type="button" onClick={() => onAction('approve-publish', record)} className="rounded-xl bg-amber-400 px-4 py-2.5 text-sm font-black text-slate-950">Approve and publish</button></> : null}{record.moderationStatus === 'APPROVED' && !record.isPublished ? <button type="button" onClick={() => onAction('publish', record)} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white">Publish</button> : null}{record.isPublished ? <button type="button" onClick={() => onAction('unpublish', record)} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700">Unpublish</button> : null}<button type="button" onClick={() => onAction('archive', record)} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold text-slate-700">Archive</button></div>
  </CommonModal>;
}
