'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { getBookingFeedbackReport } from '@/lib/booking-feedback/api';
import type { BookingFeedbackReport } from '@/lib/booking-feedback/types';
import { hasPermission, PERMISSIONS } from '@/lib/auth/permissions';
import { createExcelBlobFromRecords, escapeCsvValue } from '@/lib/excel';

function download(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }
export default function FeedbackReportPage() {
  const { user, accessToken } = useAuth();
  const [data, setData] = useState<BookingFeedbackReport | null>(null);
  const [filters, setFilters] = useState({ eventFrom: '', eventTo: '', submittedFrom: '', submittedTo: '', rating: '', search: '', questionId: '' });
  const [page, setPage] = useState(1);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const allowed = user?.role === 'company_admin' || hasPermission(user, PERMISSIONS.REPORTS_FEEDBACK_VIEW);
  const query = (pageNumber: number, limit = 100) => ({ eventFrom: filters.eventFrom, eventTo: filters.eventTo, submittedFrom: filters.submittedFrom, submittedTo: filters.submittedTo, minRating: filters.rating || undefined, maxRating: filters.rating || undefined, search: filters.search, questionId: filters.questionId, page: pageNumber, limit });
  const load = useCallback(async (pageNumber = 1) => { if (!accessToken) return; setBusy(true); setError(''); try { setData(await getBookingFeedbackReport(accessToken, query(pageNumber))); setPage(pageNumber); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load report.'); } finally { setBusy(false); } }, [accessToken, filters]);
  useEffect(() => { if (allowed) void load(1); }, [allowed, accessToken]);
  if (!allowed) return <div className="rounded-2xl bg-white p-8 text-center">You do not have access to this report.</div>;
  async function allFilteredRows() { if (!accessToken) return []; const first = await getBookingFeedbackReport(accessToken, query(1, 200)); const pages = await Promise.all(Array.from({ length: Math.max(first.pagination.pages - 1, 0) }, (_, index) => getBookingFeedbackReport(accessToken, query(index + 2, 200)))); return [...first.rows, ...pages.flatMap((result) => result.rows)]; }
  function exportRecords(rows: BookingFeedbackReport['rows']) { const questions = new Map<string, string>(); rows.forEach((row) => row.answers.forEach((answer) => questions.set(answer.questionId, answer.questionText ?? answer.questionId))); return rows.map((row) => ({ 'Booking ID': row.bookingId, Customer: row.customerName, Mobile: row.customerPhone, Event: row.eventType, 'Event Date': row.eventDate, ...Object.fromEntries([...questions].map(([id, text]) => [text, row.answers.find((answer) => answer.questionId === id)?.rating ?? ''])), 'Average Rating': row.averageRating, Comment: row.comment ?? '', Submitted: row.submittedAt, 'Internal Note': row.internalNote ?? '' })); }
  async function exportFile(format: 'csv' | 'xlsx') { setBusy(true); try { const exportRows = exportRecords(await allFilteredRows()); if (format === 'xlsx') return download(await createExcelBlobFromRecords('Booking Feedback', exportRows), 'booking-feedback-report.xlsx'); const headers = Object.keys(exportRows[0] ?? {}); const text = [headers.map(escapeCsvValue).join(','), ...exportRows.map((row) => headers.map((header) => escapeCsvValue(row[header as keyof typeof row])).join(','))].join('\n'); download(new Blob([text], { type: 'text/csv;charset=utf-8' }), 'booking-feedback-report.csv'); } finally { setBusy(false); } }
  async function printAll() { if (!data) return; setBusy(true); try { const rows = await allFilteredRows(); setData({ ...data, rows }); setTimeout(() => window.print(), 50); } finally { setBusy(false); } }
  return <main className="space-y-6 pb-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/reports" className="text-sm font-semibold text-amber-700">← Reports</Link><h1 className="mt-2 text-3xl font-black text-slate-950">Booking Feedback Report</h1><p className="mt-1 text-slate-500">Customer experience, question performance, and response tracking.</p></div><div className="flex gap-2"><button disabled={busy} onClick={() => exportFile('csv')} className="rounded-xl border bg-white px-4 py-2.5 font-semibold">CSV</button><button disabled={busy} onClick={() => exportFile('xlsx')} className="rounded-xl bg-emerald-600 px-4 py-2.5 font-semibold text-white">Excel</button><button disabled={busy} onClick={printAll} className="rounded-xl bg-slate-950 px-4 py-2.5 font-semibold text-white">Print</button></div></div>
    <section className="grid gap-3 rounded-2xl bg-white p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-4"><input type="date" title="Event from" value={filters.eventFrom} onChange={(e) => setFilters((v) => ({ ...v, eventFrom: e.target.value }))} className="rounded-xl border p-3"/><input type="date" title="Event to" value={filters.eventTo} onChange={(e) => setFilters((v) => ({ ...v, eventTo: e.target.value }))} className="rounded-xl border p-3"/><input type="date" title="Submitted from" value={filters.submittedFrom} onChange={(e) => setFilters((v) => ({ ...v, submittedFrom: e.target.value }))} className="rounded-xl border p-3"/><input type="date" title="Submitted to" value={filters.submittedTo} onChange={(e) => setFilters((v) => ({ ...v, submittedTo: e.target.value }))} className="rounded-xl border p-3"/><select value={filters.rating} onChange={(e) => setFilters((v) => ({ ...v, rating: e.target.value }))} className="rounded-xl border p-3"><option value="">All average ratings</option>{[5,4,3,2,1].map((value) => <option key={value} value={value}>Average exactly {value}</option>)}</select><select value={filters.questionId} onChange={(e) => setFilters((v) => ({ ...v, questionId: e.target.value }))} className="rounded-xl border p-3"><option value="">All questions</option>{data?.questionOptions.map((question) => <option key={question.id} value={question.id}>{question.text}</option>)}</select><input value={filters.search} onChange={(e) => setFilters((v) => ({ ...v, search: e.target.value }))} placeholder="Customer or booking" className="rounded-xl border p-3"/><button onClick={() => load(1)} disabled={busy} className="rounded-xl bg-amber-400 p-3 font-bold">{busy ? 'Loading…' : 'Apply filters'}</button></section>
    {error ? <p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p> : null}
    {data ? <><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Eligible bookings', data.summary.eligibleBookings], ['Responses', data.summary.responses], ['Response rate', `${data.summary.responseRate}%`], ['Average rating', `${data.summary.averageRating.toFixed(1)} / 5`]].map(([label, value]) => <div key={label} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Question performance</h2><div className="mt-4 space-y-3">{data.questionBreakdown.map((question) => <div key={question.id} className="grid gap-2 rounded-xl bg-slate-50 p-4 sm:grid-cols-[1fr_auto]"><span>{question.text}</span><strong>{question.averageRating.toFixed(1)} / 5 · {question.responses} responses</strong></div>)}</div></section><section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{['Customer','Event','Date','Rating','Comment','Internal note'].map((header) => <th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{data.rows.map((row) => <tr key={row.id} className="border-t"><td className="px-4 py-4 font-semibold">{row.customerName}<br/><span className="font-normal text-slate-500">{row.customerPhone}</span></td><td className="px-4 py-4">{row.eventType}</td><td className="px-4 py-4">{row.eventDate}</td><td className="px-4 py-4 font-bold text-amber-600">{row.averageRating.toFixed(1)} ★</td><td className="max-w-xs px-4 py-4">{row.comment || '—'}</td><td className="max-w-xs px-4 py-4">{row.internalNote || '—'}</td></tr>)}</tbody></table></div></section></> : null}
    {data && data.pagination.pages > 1 ? <div className="flex items-center justify-center gap-3"><button disabled={page <= 1 || busy} onClick={() => load(page - 1)} className="rounded-xl border bg-white px-4 py-2 disabled:opacity-40">Previous</button><span className="text-sm font-semibold">Page {page} of {data.pagination.pages}</span><button disabled={page >= data.pagination.pages || busy} onClick={() => load(page + 1)} className="rounded-xl border bg-white px-4 py-2 disabled:opacity-40">Next</button></div> : null}
  </main>;
}
