'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { fetchDecorationInventoryReport, fetchDecorationReportBreakdown, fetchDecorationReportSummary, fetchDecorationRevenueAnalysis, type DecorationReportFilters } from '@/lib/auth/api';
import type { DecorationInventoryReport, DecorationReportBreakdown, DecorationReportSummary, DecorationRevenueAnalysis, DecorationRevenueGroup } from '@/lib/auth/types';
import { useAuth } from '@/components/auth/auth-provider';

const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const label=(value:string)=>value.replaceAll('_',' ').toLowerCase().replace(/(^|\s)\S/g,letter=>letter.toUpperCase());
const thisMonth=()=>{const now=new Date();return`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`};
function RevenueTable({title,description,rows}:{title:string;description:string;rows:DecorationRevenueGroup[]}){return <article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="p-5"><h2 className="font-bold">{title}</h2><p className="text-sm text-slate-500">{description}</p></div>{rows.length?<><div className="space-y-3 p-4 pt-0 sm:hidden">{rows.map(row=><div key={row.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><b>{row.name}</b><span className="text-xs text-slate-500">{row.bookingCount} event{row.bookingCount===1?'':'s'}</span></div><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-xs text-slate-500">Package value</dt><dd className="font-semibold">{money(row.packageValue)}</dd></div><div><dt className="text-xs text-slate-500">Collected</dt><dd className="font-semibold text-emerald-700">{money(row.collectedAmount)}</dd></div><div><dt className="text-xs text-slate-500">Outstanding</dt><dd className="font-semibold text-red-700">{money(row.outstandingAmount)}</dd></div><div><dt className="text-xs text-slate-500">Average package</dt><dd className="font-semibold">{money(row.averagePackageValue)}</dd></div></dl></div>)}</div><div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Name</th><th className="px-4 py-3 text-right">Events</th><th className="px-4 py-3 text-right">Package</th><th className="px-4 py-3 text-right">Collected</th><th className="px-4 py-3 text-right">Outstanding</th><th className="px-5 py-3 text-right">Average</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-b last:border-0"><td className="px-5 py-4 font-semibold">{row.name}</td><td className="px-4 py-4 text-right">{row.bookingCount}</td><td className="px-4 py-4 text-right">{money(row.packageValue)}</td><td className="px-4 py-4 text-right text-emerald-700">{money(row.collectedAmount)}</td><td className="px-4 py-4 text-right text-red-700">{money(row.outstandingAmount)}</td><td className="px-5 py-4 text-right">{money(row.averagePackageValue)}</td></tr>)}</tbody></table></div></>:<p className="px-5 pb-5 text-sm text-slate-500">No committed event revenue in this period.</p>}</article>}

export default function Page(){
 const{accessToken}=useAuth(),params=useSearchParams(),router=useRouter();
 const[mode,setMode]=useState<'month'|'date'|'range'>(()=>params.has('date')?'date':params.has('from')?'range':'month');
 const[month,setMonth]=useState(params.get('month')??thisMonth()),[date,setDate]=useState(params.get('date')??''),[from,setFrom]=useState(params.get('from')??''),[to,setTo]=useState(params.get('to')??'');
 const[summary,setSummary]=useState<DecorationReportSummary|null>(null),[breakdown,setBreakdown]=useState<DecorationReportBreakdown|null>(null),[revenue,setRevenue]=useState<DecorationRevenueAnalysis|null>(null),[inventory,setInventory]=useState<DecorationInventoryReport|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const filters=useMemo<DecorationReportFilters>(()=>mode==='month'?{month}:mode==='date'?{date}:{from,to},[mode,month,date,from,to]);
 const load=useCallback(async()=>{if(!accessToken)return;try{setLoading(true);setError('');const[s,b,r,i]=await Promise.all([fetchDecorationReportSummary(accessToken,filters),fetchDecorationReportBreakdown(accessToken,filters),fetchDecorationRevenueAnalysis(accessToken,filters),fetchDecorationInventoryReport(accessToken,filters)]);setSummary(s);setBreakdown(b);setRevenue(r);setInventory(i);const query=new URLSearchParams(filters as Record<string,string>);router.replace(`/decoration/reports?${query}`)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load decoration reports.')}finally{setLoading(false)}},[accessToken,filters,router]);
 useEffect(()=>{void load()},[load]);
 const maxStatus=Math.max(1,...(breakdown?.statuses.map(item=>item.count)??[]));
 return <section className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
  <header><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Event Decoration</p><h1 className="text-2xl font-bold text-slate-900">Business Reports</h1><p className="mt-1 text-sm text-slate-500">Financial health, inquiry conversion and event progress in one place.</p></header>
  <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-2">{(['month','date','range'] as const).map(value=><button key={value} onClick={()=>setMode(value)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode===value?'bg-slate-900 text-white':'bg-slate-100 text-slate-600'}`}>{value==='range'?'Custom range':label(value)}</button>)}</div><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-end">{mode==='month'&&<label className="text-sm font-medium">Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="mt-1 block rounded-lg border px-3 py-2"/></label>}{mode==='date'&&<label className="text-sm font-medium">Event date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 block rounded-lg border px-3 py-2"/></label>}{mode==='range'&&<><label className="text-sm font-medium">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 block rounded-lg border px-3 py-2"/></label><label className="text-sm font-medium">To<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 block rounded-lg border px-3 py-2"/></label></>}<button onClick={()=>void load()} disabled={loading||(mode==='date'&&!date)||(mode==='range'&&(!from||!to))} className="rounded-lg bg-amber-500 px-4 py-2 font-semibold text-white disabled:opacity-50">Apply</button></div></div>
  {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700"><b>Reports could not be loaded.</b><p className="text-sm">{error}</p><button onClick={()=>void load()} className="mt-2 text-sm font-semibold underline">Try again</button></div>}
  {loading?<div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({length:8},(_,index)=><div key={index} className="h-24 animate-pulse rounded-2xl bg-slate-100"/>)}</div>:summary&&breakdown&&revenue&&inventory?<>
   <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Total events',summary.totalEvents],['Confirmed',summary.confirmedCount],['Completed',summary.completedCount],['Conversion',`${breakdown.conversion.conversionRate}%`],['Package value',money(summary.totalPackageValue)],['Advance received',money(summary.advanceReceived)],['Total collected',money(summary.totalCollected)],['Outstanding',money(summary.outstandingAmount)]].map(([name,value])=><article key={String(name)} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-medium text-slate-500">{name}</p><p className="mt-2 break-words text-xl font-bold text-slate-900 sm:text-2xl">{value}</p></article>)}</div>
   {summary.totalEvents===0?<div className="rounded-2xl border border-dashed bg-white p-10 text-center"><h2 className="font-semibold">No events in this period</h2><p className="mt-1 text-sm text-slate-500">Change the date filter to view report activity.</p></div>:<div className="grid gap-5 lg:grid-cols-2">
    <article className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Event status</h2><p className="text-sm text-slate-500">Current stage of every event in this period.</p><div className="mt-5 space-y-4">{breakdown.statuses.map(item=><div key={item.status}><div className="mb-1 flex justify-between text-sm"><span>{label(item.status)}</span><b>{item.count}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-500" style={{width:`${(item.count/maxStatus)*100}%`}}/></div></div>)}</div></article>
    <article className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">Payment position</h2><p className="text-sm text-slate-500">Cancelled and closed inquiries are excluded.</p><div className="mt-5 grid grid-cols-3 gap-2">{[['Paid',breakdown.payments.paid,'text-emerald-700 bg-emerald-50'],['Partial',breakdown.payments.partial,'text-amber-700 bg-amber-50'],['Unpaid',breakdown.payments.unpaid,'text-red-700 bg-red-50']].map(([name,value,color])=><div key={String(name)} className={`rounded-xl p-3 text-center ${color}`}><p className="text-xs">{name}</p><b className="text-xl">{value}</b></div>)}</div><div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="flex justify-between text-sm"><span>Converted events</span><b>{breakdown.conversion.convertedEvents} / {breakdown.conversion.eligibleInquiries}</b></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-500" style={{width:`${Math.min(100,breakdown.conversion.conversionRate)}%`}}/></div></div></article>
   </div>}
   <div className="grid gap-5 xl:grid-cols-2"><RevenueTable title="Revenue by event type" description="Committed booking value and payment realization by event category." rows={revenue.byEventType}/><RevenueTable title="Revenue by venue" description="Committed booking value and payment realization by venue." rows={revenue.byVenue}/></div>
   <section className="space-y-4"><div><h2 className="text-xl font-bold">Inventory operations</h2><p className="text-sm text-slate-500">Usage, peak utilization, allocation conflicts and maintenance for the selected period.</p></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Used items',`${inventory.summary.usedItems} / ${inventory.summary.totalItems}`],['Reservations',inventory.summary.totalReservations],['High utilization',inventory.summary.highUtilizationItems],['Conflicts',inventory.summary.conflictCount]].map(([name,value])=><article key={String(name)} className={`rounded-2xl border p-4 shadow-sm ${name==='Conflicts'&&Number(value)>0?'border-red-200 bg-red-50':'bg-white'}`}><p className="text-xs text-slate-500">{name}</p><p className="mt-2 text-2xl font-bold">{value}</p></article>)}</div>
    <article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="p-5"><h3 className="font-bold">Item utilization</h3><p className="text-sm text-slate-500">Peak simultaneous demand compared with serviceable quantity.</p></div>{inventory.items.length?<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-y bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Item</th><th className="px-3 py-3 text-right">Events</th><th className="px-3 py-3 text-right">Reserved</th><th className="px-3 py-3 text-right">Peak / serviceable</th><th className="px-3 py-3 text-right">Utilization</th><th className="px-5 py-3 text-right">Conflicts</th></tr></thead><tbody>{inventory.items.map(item=><tr key={item.itemId} className="border-b last:border-0"><td className="px-5 py-4"><b>{item.itemName}</b><p className="text-xs text-slate-500">{item.trackingMode}</p></td><td className="px-3 py-4 text-right">{item.eventCount}</td><td className="px-3 py-4 text-right">{item.reservedQuantity}</td><td className="px-3 py-4 text-right">{item.peakReservedQuantity} / {item.serviceableQuantity}</td><td className="px-3 py-4 text-right"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.utilizationRate>100?'bg-red-100 text-red-700':item.utilizationRate>=80?'bg-amber-100 text-amber-700':'bg-emerald-50 text-emerald-700'}`}>{item.utilizationRate}%</span></td><td className={`px-5 py-4 text-right font-semibold ${item.conflictCount?'text-red-700':'text-slate-400'}`}>{item.conflictCount}</td></tr>)}</tbody></table></div>:<p className="px-5 pb-5 text-sm text-slate-500">No active inventory is configured.</p>}</article>
    <article className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Maintenance exposure</h3><p className="text-sm text-slate-500">Current inventory unavailable for allocation.</p>{inventory.maintenance.length?<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{inventory.maintenance.map(item=><div key={item.itemId} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><b>{item.itemName}</b><span className="text-sm font-semibold text-amber-700">{item.maintenanceRate}%</span></div><p className="mt-2 text-sm text-slate-600">{item.maintenanceQuantity} of {item.totalQuantity} unavailable</p>{item.affectedUnits.length>0&&<p className="mt-2 text-xs text-slate-500">Units: {item.affectedUnits.map(unit=>unit.code).join(', ')}</p>}</div>)}</div>:<p className="mt-4 text-sm text-emerald-700">No active inventory is under maintenance.</p>}</article>
   </section>
  </>:null}
 </section>
}
