'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/components/auth/auth-provider';
import { CommonModal } from '@/components/ui/common-modal';
import { fetchDecorationCategories, fetchDecorationItems, saveDecorationCategory, saveDecorationItem, setDecorationCategoryActive, setDecorationItemActive, uploadDecorationItemImage } from '@/lib/auth/api';
import { hasPermission, PERMISSIONS } from '@/lib/auth/permissions';
import { DecorationCategory, DecorationItem } from '@/lib/auth/types';
const input='w-full rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none focus:border-amber-400';
export default function Page(){
 const {accessToken,user}=useAuth(); const manage=user?.role==='company_admin'||hasPermission(user,PERMISSIONS.DECORATION_CATALOG_MANAGE);
 const [categories,setCategories]=useState<DecorationCategory[]>([]),[items,setItems]=useState<DecorationItem[]>([]),[categoryId,setCategoryId]=useState(''),[inactive,setInactive]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [cat,setCat]=useState<DecorationCategory|'new'|null>(null),[catName,setCatName]=useState(''),[catDesc,setCatDesc]=useState('');
 const [item,setItem]=useState<DecorationItem|'new'|null>(null),[form,setForm]=useState({name:'',description:'',trackingMode:'BULK',quantity:'1',maintenance:'0',units:'',logisticsMode:'SETUP_REMOVAL',setup:'0',removal:'0',turnaround:'0',storage:''});
 const load=useCallback(async()=>{if(!accessToken)return;try{setBusy(true);const [c,i]=await Promise.all([fetchDecorationCategories(accessToken,inactive),fetchDecorationItems(accessToken,categoryId,inactive)]);setCategories(c);setItems(i);}catch(e){setError(e instanceof Error?e.message:'Unable to load catalog.');}finally{setBusy(false)}},[accessToken,categoryId,inactive]); useEffect(()=>{void load()},[load]);
 async function act(fn:()=>Promise<unknown>){setError('');try{setBusy(true);await fn();await load();return true}catch(e){setError(e instanceof Error?e.message:'Request failed.');return false}finally{setBusy(false)}}
 function openCat(v:DecorationCategory|'new'){setCat(v);setCatName(v==='new'?'':v.name);setCatDesc(v==='new'?'':v.description??'')}
 async function submitCat(e:FormEvent){e.preventDefault();if(!accessToken||!cat)return;const ok=await act(()=>saveDecorationCategory(accessToken,{name:catName,description:catDesc},cat==='new'?undefined:cat.id));if(ok)setCat(null)}
 function openItem(v:DecorationItem|'new'){setItem(v);if(v==='new')setForm({name:'',description:'',trackingMode:'BULK',quantity:'1',maintenance:'0',units:'',logisticsMode:'SETUP_REMOVAL',setup:'0',removal:'0',turnaround:'0',storage:''});else setForm({name:v.name,description:v.description??'',trackingMode:v.trackingMode,quantity:String(v.totalQuantity),maintenance:String(v.maintenanceQuantity),units:v.units.map(x=>`${x.code}|${x.status}`).join('\n'),logisticsMode:v.logisticsMode,setup:String(v.setupBufferMinutes),removal:String(v.removalBufferMinutes),turnaround:String(v.turnaroundBufferMinutes),storage:v.storageNote??''})}
 async function submitItem(e:FormEvent){e.preventDefault();if(!accessToken||!item||!categoryId)return;const units=form.units.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const [code,status]=x.split('|');return{code,status:status||'AVAILABLE'}});const ok=await act(()=>saveDecorationItem(accessToken,{categoryId,name:form.name,description:form.description,trackingMode:form.trackingMode,totalQuantity:Number(form.quantity),maintenanceQuantity:Number(form.maintenance),units,logisticsMode:form.logisticsMode,setupBufferMinutes:Number(form.setup),removalBufferMinutes:Number(form.removal),turnaroundBufferMinutes:Number(form.turnaround),storageNote:form.storage},item==='new'?undefined:item.id));if(ok)setItem(null)}
 return <section className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6 lg:p-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Event Decoration</p><h1 className="text-2xl font-bold">Catalog & Inventory</h1><p className="text-sm text-slate-500">Manage reusable decoration choices, images, quantities and logistics.</p></div>{manage&&<div className="flex gap-2"><button onClick={()=>openCat('new')} className="rounded-xl border px-4 py-2 text-sm font-semibold">Add category</button><button disabled={!categoryId} onClick={()=>openItem('new')} className="rounded-xl bg-amber-500 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Add item</button></div>}</div>
 {error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex gap-2 overflow-x-auto pb-2"><button onClick={()=>setCategoryId('')} className={`rounded-full px-4 py-2 text-sm ${!categoryId?'bg-slate-900 text-white':'bg-slate-100'}`}>All</button>{categories.map(c=><button key={c.id} onClick={()=>setCategoryId(c.id)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${categoryId===c.id?'bg-slate-900 text-white':'bg-slate-100'} ${c.isActive?'':'opacity-50'}`}>{c.name}</button>)}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={inactive} onChange={e=>setInactive(e.target.checked)}/> Show inactive</label>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(v=><article key={v.id} className={`overflow-hidden rounded-2xl border bg-white shadow-sm ${v.isActive?'':'opacity-60'}`}><div className="aspect-[16/10] bg-slate-100">{v.images.find(x=>x.isCover)||v.images[0]?<img src={(v.images.find(x=>x.isCover)||v.images[0]).url} alt={v.name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-sm text-slate-400">No image</div>}</div><div className="p-4"><div className="flex justify-between"><h2 className="font-semibold">{v.name}</h2><span className="text-xs text-slate-500">{v.availableQuantity}/{v.totalQuantity} available</span></div><p className="mt-1 text-xs text-slate-500">{v.trackingMode} · {v.logisticsMode}</p>{manage&&<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>openItem(v)} className="rounded-lg border px-3 py-2 text-xs">Edit</button><label className="cursor-pointer rounded-lg border px-3 py-2 text-xs">Add image<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f&&accessToken)void act(()=>uploadDecorationItemImage(accessToken,v.id,f))}}/></label><button onClick={()=>accessToken&&void act(()=>setDecorationItemActive(accessToken,v.id,!v.isActive))} className="rounded-lg border px-3 py-2 text-xs">{v.isActive?'Deactivate':'Activate'}</button></div>}</div></article>)}</div>{busy&&<p className="text-center text-sm text-slate-500">Updating catalog…</p>}
 <div className="grid gap-3 sm:grid-cols-2">{manage&&categories.map(c=><div key={c.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span>{c.name}</span><span className="flex gap-2"><button onClick={()=>openCat(c)}>Edit</button><button onClick={()=>accessToken&&void act(()=>setDecorationCategoryActive(accessToken,c.id,!c.isActive))}>{c.isActive?'Deactivate':'Activate'}</button></span></div>)}</div>
 {cat&&<CommonModal title={cat==='new'?'Add category':'Edit category'} onClose={()=>setCat(null)} widthClassName="max-w-lg"><form onSubmit={submitCat} className="space-y-3"><input required maxLength={100} value={catName} onChange={e=>setCatName(e.target.value)} placeholder="Category name" className={input}/><textarea value={catDesc} onChange={e=>setCatDesc(e.target.value)} placeholder="Description" className={input}/><button disabled={busy} className="w-full rounded-xl bg-amber-500 p-3 font-semibold text-white">Save</button></form></CommonModal>}
 {item&&<CommonModal title={item==='new'?'Add decoration item':'Edit decoration item'} onClose={()=>setItem(null)}><form onSubmit={submitItem} className="grid gap-3 sm:grid-cols-2"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Item name" className={input}/><select value={form.trackingMode} onChange={e=>setForm({...form,trackingMode:e.target.value})} className={input}><option value="BULK">Bulk quantity</option><option value="TAGGED">Individually tagged</option></select><input type="number" min="0" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} placeholder="Total quantity" className={input}/><input type="number" min="0" value={form.maintenance} onChange={e=>setForm({...form,maintenance:e.target.value})} placeholder="Maintenance quantity" className={input}/><select value={form.logisticsMode} onChange={e=>setForm({...form,logisticsMode:e.target.value})} className={input}><option value="SETUP_REMOVAL">Setup & removal</option><option value="SLOT_ONLY">Slot only</option><option value="MOBILE_TURNAROUND">Mobile turnaround</option></select><input value={form.storage} onChange={e=>setForm({...form,storage:e.target.value})} placeholder="Storage note" className={input}/>{form.trackingMode==='TAGGED'&&<textarea required value={form.units} onChange={e=>setForm({...form,units:e.target.value})} placeholder={'One unit per line: CODE|STATUS\nSF-01|AVAILABLE'} className={`${input} sm:col-span-2`} rows={5}/>}<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" className={`${input} sm:col-span-2`}/><button disabled={busy} className="rounded-xl bg-amber-500 p-3 font-semibold text-white sm:col-span-2">Save item</button></form></CommonModal>}</section>
}
