'use client';
import { useEffect, useState } from 'react';
import { AppSettings } from '@/lib/auth/types';
import { updateBookingFeedbackSettings } from '@/lib/booking-feedback/api';
import { useToast } from '@/components/ui/toast';

export function BookingFeedbackSettings({ accessToken, settings, onSaved }: { accessToken: string; settings: AppSettings; onSaved: (settings: AppSettings) => void }) {
  const [enabled, setEnabled] = useState(Boolean(settings.enableBookingFeedback));
  const [questions, setQuestions] = useState(settings.bookingFeedbackQuestions ?? []);
  const [saving, setSaving] = useState(false); const { showToast } = useToast();
  useEffect(() => { setEnabled(Boolean(settings.enableBookingFeedback)); setQuestions(settings.bookingFeedbackQuestions ?? []); }, [settings]);
  const update = (index: number, patch: Partial<(typeof questions)[number]>) => setQuestions((current) => current.map((item, i) => i === index ? { ...item, ...patch } : item));
  const move = (index: number, offset: -1 | 1) => setQuestions((current) => { const target = index + offset; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  async function save() { const active = questions.filter((item) => item.active); if (enabled && (active.length < 1 || active.length > 10)) { showToast('Keep between 1 and 10 active questions.', 'error'); return; } if (questions.some((item) => !item.text.trim())) { showToast('Every question needs text.', 'error'); return; } try { setSaving(true); const next = await updateBookingFeedbackSettings(accessToken, { enableBookingFeedback: enabled, questions: questions.map((item, index) => ({ ...item, text: item.text.trim(), displayOrder: index })) }); onSaved(next); showToast('Booking feedback settings updated.', 'success'); } catch (error) { showToast(error instanceof Error ? error.message : 'Unable to save feedback settings.', 'error'); } finally { setSaving(false); } }
  return <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Customer experience</p><h2 className="mt-1 text-xl font-bold text-slate-900">Booking Feedback</h2><p className="mt-1 text-sm text-slate-600">Collect one rating response after a completed event.</p></div><label className="flex items-center gap-3 font-semibold"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} className="h-5 w-5"/> Enabled</label></div>
    <div className="mt-5 space-y-3">{questions.map((question, index) => <div key={question.id} className="grid gap-3 rounded-2xl border border-slate-200 p-3 sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="font-bold text-slate-500">{index + 1}</span><input value={question.text} onChange={(e) => update(index, { text: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2"/><div className="flex flex-wrap gap-2"><button type="button" disabled={index === 0} onClick={() => move(index, -1)} className="rounded-lg border px-2 disabled:opacity-30" aria-label="Move question up">↑</button><button type="button" disabled={index === questions.length - 1} onClick={() => move(index, 1)} className="rounded-lg border px-2 disabled:opacity-30" aria-label="Move question down">↓</button><label className="flex items-center gap-1 text-sm"><input type="checkbox" checked={question.active} onChange={(e) => update(index, { active: e.target.checked })}/> Active</label><button type="button" onClick={() => setQuestions((items) => items.filter((_, i) => i !== index))} className="rounded-lg border px-2 text-red-600">Remove</button></div></div>)}</div>
    <div className="mt-4 flex flex-wrap justify-between gap-3"><button type="button" disabled={questions.length >= 10} onClick={() => setQuestions((items) => [...items, { id: crypto.randomUUID(), text: '', active: true, displayOrder: items.length }])} className="rounded-xl border px-4 py-2 font-semibold">+ Add question</button><button type="button" disabled={saving} onClick={() => void save()} className="rounded-xl bg-amber-400 px-5 py-2 font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save feedback settings'}</button></div>
  </section>;
}
