import { strict as assert } from 'node:assert';
import { bookingFeedbackAverage, buildBookingFeedbackAnswers, canShowBookingFeedbackAction, feedbackDisplayLabel, isLowBookingFeedback, normalizeBookingFeedbackExpiryDays, resolveBookingFeedbackQuestions, validateFollowUpInput, validateStaffFeedbackCapture } from './domain';
const valid = { enabled: true, status: 'COMPLETED' as const, eventDate: '2026-08-31', today: '2026-09-01', canManage: true };
assert.equal(canShowBookingFeedbackAction(valid), true);
assert.equal(canShowBookingFeedbackAction({ ...valid, status: 'CONFIRMED' }), true);
assert.equal(canShowBookingFeedbackAction({ ...valid, eventDate: '2026-09-01' }), false);
assert.equal(canShowBookingFeedbackAction({ ...valid, status: 'CANCELLED' }), false);
assert.equal(canShowBookingFeedbackAction({ ...valid, enabled: false }), false);
assert.equal(bookingFeedbackAverage([5, 4, 4]), 4.33);
assert.equal(resolveBookingFeedbackQuestions([]).length, 5);
assert.equal(resolveBookingFeedbackQuestions(undefined)[0].id, 'overall-experience');
assert.deepEqual(resolveBookingFeedbackQuestions([{ id: 'custom', text: 'Custom?', active: true, displayOrder: 0 }]), [{ id: 'custom', text: 'Custom?', active: true, displayOrder: 0 }]);
const publicQuestions = [{ id: 'q1', text: 'One?', displayOrder: 0 }, { id: 'q2', text: 'Two?', displayOrder: 1 }];
assert.deepEqual(buildBookingFeedbackAnswers(publicQuestions, { q2: 4 }), [{ questionId: 'q2', rating: 4 }]);
assert.throws(() => buildBookingFeedbackAnswers(publicQuestions, {}), /at least one question/i);
assert.doesNotThrow(() => validateStaffFeedbackCapture({ captureMethod: 'PHONE', consentConfirmed: true }));
assert.throws(() => validateStaffFeedbackCapture({ captureMethod: '', consentConfirmed: true }), /captured/i);
assert.throws(() => validateStaffFeedbackCapture({ captureMethod: 'OTHER', captureMethodOther: '', consentConfirmed: true }), /describe/i);
assert.throws(() => validateStaffFeedbackCapture({ captureMethod: 'EMAIL', consentConfirmed: false }), /confirm/i);
assert.equal(normalizeBookingFeedbackExpiryDays(undefined), 15);
assert.equal(normalizeBookingFeedbackExpiryDays(30), 30);
assert.equal(normalizeBookingFeedbackExpiryDays(0), 1);
assert.equal(normalizeBookingFeedbackExpiryDays(100), 90);
assert.equal(feedbackDisplayLabel('NOT_REQUESTED'), 'Feedback');
assert.equal(feedbackDisplayLabel('WAITING'), 'Feedback · Waiting');
assert.equal(feedbackDisplayLabel('RECEIVED'), 'Feedback · Received');
assert.equal(feedbackDisplayLabel('STAFF_RECORDED'), 'Feedback · Staff recorded');
assert.equal(isLowBookingFeedback(2), true);
assert.equal(isLowBookingFeedback(2.01), false);
assert.doesNotThrow(() => validateFollowUpInput('Customer requested a callback'));
assert.throws(() => validateFollowUpInput('  '), /note/i);
